### ISSUE TITLE
Import bank holidays from google

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#100]
New dialog probably?

**Comment by jekuno** [comment]
Or simply import holidays from a public API such as https://holidayapi.com/ which has a Node.js API as well: https://github.com/joshtronic/node-holidayapi

**Comment by vpp** [comment]
hi @jekuno!

thank you for those links

(I was not aware of this service)

**Comment by vpp** [comment]
It appeared that holidayapi.com has quite expensive package to suite our needs so probably worth re-using some other resources as http://www.officeholidays.com/countries/index.php

**Comment by jekuno** [comment]
Oh sorry, I thought holidayapi.com was a free service. It seems as if officeholidays.com doesn't offer an API, does it?

**Comment by vpp** [comment]
The holidayapi.com offers free historical data..

I was thinking scraping officeholidays.com, not sure about there license though... This needs to be clarified.

**Comment by jekuno** [comment]
I think in the long run we need a reliable API because dates of certain holidays differ from year to year. So you would have to scrape the website on a regular base which is very error prone (will break sooner or later).

**Comment by vpp** [comment]
Absolutely!

I just had an idea to allow customers to use https://holidayapi.com/ by purchasing their API token and linking it to the TimeOff.management account.

I need to elaborate on this more.

**Comment by jekuno** [comment]
You're right it's quite expensive. Only big companies will be willing to spend $135 a year just for receiving maybe 20 dates per year.

Maybe there are free alternatives which offer an API?

**Comment by vpp** [comment]
For instance this does not promise easy ride: https://opendata.stackexchange.com/questions/1926/list-of-public-holidays-by-countries

**Comment by jekuno** [comment]
https://github.com/novafloss/workalendar looks interesting.

**Comment by vpp** [comment]
yeah

**Comment by vpp** [comment]
Ended up using https://github.com/vpp/date-holidays

**Comment by vpp** [comment]
Now system use set of default holidays when creating new account.

What is left: to add ability to update current year's bank holidays for existing account.

**Comment by vpp** [comment]
Just added ability to import default bank holidays into existing accounts.
