### ISSUE TITLE
Date format selection bug: new absence

### ISSUE THREAD

**Issue by enriquetoledano** [timeoff-management/application#104]
Hi:

There's a bug using the date format DD/MM/YYYY. When I create a new leave request with one or more days (for example 01 May to 05 May) it fails:
![leavefail](https://cloud.githubusercontent.com/assets/22968312/21923123/8d1e5fb6-d972-11e6-8c18-0fe9743da49b.jpg)
I think there problem is in leave_request.js

Best regards

**Comment by vpp** [comment]
Hi @enriquetoledano, thank you for reporting this issue.

I will have a look at it ASAP.

**Comment by jekuno** [comment]
I can confirm this bug.

**Comment by vpp** [comment]
hi @jekuno, 

the fix is still in progress..

**Comment by vpp** [comment]
Should be fixed now.
