### ISSUE TITLE
Successfully Secured with SSL

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#112]
Hi Pavlo, 

I just thought I'd update you that I've been able to secure the application with SSL.

Here's the lines of code I added to app.js
`var fs = require('fs'),
https = require('https'),
 
app = express();
 
https.createServer({
  key: fs.readFileSync('10.10.10.132.key'),
  cert: fs.readFileSync('10.10.10.132.cert')
}, app).listen(443);
 
//Redirect from http to https
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(301, { "Location": "https://" + req.headers['host'] + req.url });
  res.end();
}).listen(80);`

**Comment by vpp** [comment]
hi @AsimPervez93!

Thank you for sharing.

It came just in time as chrome started to moan about insecurity when login form is on non https page.. So TimeOff.Management needs to move to the https.
