### ISSUE TITLE
Email Encryption?

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#113]
Hi @vpp, 

I'm still having trouble getting email to work.  I know that my email host required all email to be encrypted or it will not work.

Are the emails from the app encrypted?  Is the email encryption different to securing the domain on SSL?

Kind Regards,

**Comment by AsimPervez93** [comment]
I've sorted this out.  I had to add an extra line to app.json as below:

`{
  "allow_create_new_accounts" : true,
  "send_emails"              : false,
  "application_sender_email" : "email@test.com",
  "email_transporter" : {
    "host" : "localhost",
    "port" : 25,
    **"secure" : true,**
    "auth" : {
      "user" : "user",
      "pass" : "pass"
    }
  },
  "crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_"
}
`

**Comment by vpp** [comment]
hi @AsimPervez93, thank you for sharing.

I think this kind of info needs to be on some kind of wiki, or even as comments in config.

I will have a thought on how to not loose it.
