### ISSUE TITLE
Add option to count holidays per fiscal year

### ISSUE THREAD

**Issue by nnmalex** [timeoff-management/application#114]
Some companies count holidays and sick leaves in fiscal year (April 1 - March 31 in my case) rather than calendar years (Jan 1 - Dec 31).

**Comment by vpp** [comment]
Fair point @nnmalex.

It is indeed worth making it configurable to set the company's start of the year date.

**Comment by hansg01** [comment]
@vpp db schema for the table Companies has a column `start_of_new_year`, is that month index which can be changed?

**Comment by vpp** [comment]
@hansg01, this is just a place where the start date is going to be stored. Unfortunately this is not respected in all calculations yet. So changes to the value will not have any effect.

**Comment by nnmalex** [comment]
Hello @vpp,

Is this a difficult fix? I didn’t look into code for this yet but from the top of your head can this be hard coded on a certain app instance easier than implementing as a feature?

**Comment by vpp** [comment]
It is doable but not trivial unfortunately.

Simple grep and replace would not work as one needs manually update code like this

https://github.com/timeoff-management/application/blob/master/lib/model/mixin/user/absence_aware.js#L194

**Comment by vpp** [comment]
It is not big set of places though:
```
lib//model/calendar_month.js:9:    this.date           = moment(day).startOf('month');
lib//model/db/user.js:489:          { end_date : {$gte : moment().startOf('day').format('YYYY-MM-DD') }},
lib//model/mixin/user/absence_aware.js:29:      return moment().add(delta, 'months').startOf('month');
lib//model/mixin/user/absence_aware.js:72:                  moment(year).startOf('year').format('YYYY-MM-DD'),
lib//model/mixin/user/absence_aware.js:80:                  moment( year ).startOf('year').format('YYYY-MM-DD'),
lib//model/mixin/user/absence_aware.js:194:            moment(year).startOf('year').format('YYYY-MM-DD'),
lib//model/mixin/user/absence_aware.js:200:            moment(year).startOf('year').format('YYYY-MM-DD'),
lib//model/mixin/user/absence_aware.js:438:      : now.startOf('year'),
lib//model/mixin/user/absence_aware.js:480:              moment(year).startOf('year').format('YYYY-MM-DD'),
lib//model/mixin/user/absence_aware.js:486:              moment(year).startOf('year').format('YYYY-MM-DD'),
lib//model/mixin/user/company_aware.js:47:                      moment().startOf('year').format('YYYY-MM-DD'),
lib//model/mixin/user/company_aware.js:53:                      moment().startOf('year').format('YYYY-MM-DD'),
lib//route/users.js:240:        moment( new_user_attributes.end_date ).startOf('day').toDate() >= moment().startOf('day').toDate()
lib//route/users.js:519:                      moment().startOf('year').format('YYYY-MM-DD'),
lib//route/users.js:525:                      moment().startOf('year').format('YYYY-MM-DD'),
```

**Comment by nnmalex** [comment]
Will check it out, thanks!

**Comment by cadab** [comment]
Was this change attempted?
