### ISSUE TITLE
Holiday Allowance Don't Match

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#115]
Hi @vpp 

I've created a user which has the following total allowance: 
![image](https://cloud.githubusercontent.com/assets/17923501/23207648/ea84d428-f8e9-11e6-9473-1b2151ec823c.png)

However, the user is in the Sales group which has an allowance of 20:
![image](https://cloud.githubusercontent.com/assets/17923501/23207665/ff9d92be-f8e9-11e6-8d45-b156dcb376d0.png)

How come there is 2 days missing?

**Comment by vpp** [comment]
hi @AsimPervez93,

It is possible that start date for your user was not at immediate start of current year, so system calculated proportional allowance. Other option could be that user has manual adjustments.
