### ISSUE TITLE
Users able to change their passwords

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#117]
Hi @vpp 

Just a feature request. It would be good if we could allow users to be able to change their passwords once they are logged in.

Kind Regards,
Asim Pervez

**Comment by AsimPervez93** [comment]
I know users can simply reset their password using forgot password but maybe it would be a nice feature for a future update if they could update their password within their profile.

**Comment by vpp** [comment]
Hi Asim,

It is reasonable feature.

Let's have this ticket opened.
