### ISSUE TITLE
Default Type of Leave to Holiday

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#118]
Hi @vpp 

Is there a way I can default the Leave Type in the New Absence form to default to Holidays instead of alphabetical order?

![image](https://cloud.githubusercontent.com/assets/17923501/23356099/880fd33e-fcd0-11e6-9069-ae94ea7d05de.png)

Kind Regards,
Asim Pervez

**Comment by HyperSquiZ** [comment]
Currently, I don;t think so.

I have worked around this by naming my Leave Types "1. Holiday" "2. Dependant Care Leave" "3. Sick Leave" etc (for now)

**Comment by vpp** [comment]
@HyperSquiZ, nice, thanks for sharing (as a quick work around it could help)

**Comment by vpp** [comment]
Done as part of #212
