### ISSUE TITLE
No 'Default Date' Option in General Settings

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#119]
In my test instance I have the following options in General settings: 

Company Name:
Country:
Date Format:

However, in my live instance, I don't have the Date Format option, only Company Name and Country.

Why might this be?

**Comment by vpp** [comment]
hi @AsimPervez93,

Make sure your live instance has the most recent version of code.

Please ensure that you do following when updating code of live version:

https://github.com/timeoff-management/application#updating-existing-instance-with-new-code

**Comment by AsimPervez93** [comment]
Hi @vpp 

I get stuck at the db update script with the following error:

Error: Cannot find module '/var/www/html/application/node_modules/.bin/sequelize'

**Comment by vpp** [comment]
Hi AsimPervez93,

Consider running

npm install

**Comment by AsimPervez93** [comment]
Hi @vpp 

I tried that and still get the error at the db-update script:

> Error: Cannot find module '/var/www/html/application/node_modules/.bin/sequelize'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> 
> npm ERR! Linux 4.4.0-64-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "db-update"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! jswebapp@0.0.0 db-update: `node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the jswebapp@0.0.0 db-update script 'node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the jswebapp package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs jswebapp
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls jswebapp
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/www/html/application/npm-debug.log

**Comment by vpp** [comment]
hi @AsimPervez93,

Do you have "node_modules" in the checkout directory?

If so can you send what directories are there?

The idea of the failing command is to run the "sequelize" file. Can you have quick look around to check if maybe it is in some other place?

**Comment by vpp** [comment]
@AsimPervez93, one more point, for migrations the system uses the sequelize-cli tool:

http://docs.sequelizejs.com/en/v3/docs/migrations/#the-cli

Please check how they suggest to install it.

I've used local installation and it worked. Maybe you can consider global installation?

**Comment by AsimPervez93** [comment]
@vpp 

I'm not sure what was causing this.  I ran apt-get update and apt-get upgrade, then restarted the machine.

Then ran npm install again and this seemed to have worked.  I successfully was able to update from git.  I know this has worked because the app.js has returned to default.

**Comment by vpp** [comment]
@AsimPervez93 

Does it mean that the issue is sorted?

**Comment by AsimPervez93** [comment]
@vpp 

I'm just testing it just now.  I'll comment again in 15 mins or so once I've tested the Date format.

**Comment by AsimPervez93** [comment]
Hi @vpp 

I get this error after logging in:

>Missing helper: "as_date_formatted"

> Error: Missing helper: "as_date_formatted"
>     at Object.<anonymous> (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
>     at eval (eval at createFunctionContext (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:3:130)
>     at Object.prog [as inverse] (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
>     at Object.<anonymous> (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/helpers/if.js:17:22)
>     at eval (eval at createFunctionContext (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:8:32)
>     at prog (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/runtime.js:219:12)
>     at execIteration (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:51:19)
>     at Object.<anonymous> (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/helpers/each.js:61:13)
>     at Object.eval (eval at createFunctionContext (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:42:31)
>     at main (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
>     at ret (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
>     at ret (/var/www/html/application/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
>     at ExpressHandlebars._renderTemplate (/var/www/html/application/node_modules/express-handlebars/lib/express-handlebars.js:247:12)
>     at ExpressHandlebars.<anonymous> (/var/www/html/application/node_modules/express-handlebars/lib/express-handlebars.js:173:21)

**Comment by AsimPervez93** [comment]
Hi @vpp 

Again, I'm not sure what caused this but I was able to resolve it by deleting the entire application folder and restoring a backup version, then doing the npm install again, then updating the git files.

Since updating the files, I can confirm that the Date format is now present in the General Settings.
