### ISSUE TITLE
Cancel pending PTO request

### ISSUE THREAD

**Issue by sgusler** [timeoff-management/application#120]
Employees would like the ability to cancel PTO requests submitted in error while they're still in the pending status.

**Comment by vpp** [comment]
Thank you, @sgusler for suggestion.

Looks reasonable and not hard to implement.

**Comment by mladenmilev** [comment]
I agree. I find this useful and required also, alse the yhave to bug the boss to reject their request and they create a new one.

**Comment by vpp** [comment]
Another customer complained about this annoyance.

**Comment by mladenmilev** [comment]
Thinking again about this: different actions have different "_approvers_". 

* Requesting absence: managers and manager deledates. Optionally auto approve.
* Canceling Approved absence: *self*; manager, delegated managers. Optionally auto approve.
* Canceling Pending Absence : *self*; manager, delegated managers. Optionally auto approve.

**Comment by vpp** [comment]
hi @mladenmilev, was the last comment about multiple approvers? (#82)

**Comment by mladenmilev** [comment]
@vpp yes, consider it towards #82. Should I delete my comment from this thread and add it to the other ?

**Comment by vpp** [comment]
@mladenmilev, no worries, I will move it over

**Comment by vpp** [comment]
The feature is in master under v0.5.0 tag.
