### ISSUE TITLE
Can't Adjust Allownace by Negative .5

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#122]
Hi @vpp 

I've encountered an issue where I can't adjust the allowance by -8.5.  This user should have 16.5 days allowance but I can only give 16 or 17.  It won't allow me to do -8.5.

![image](https://cloud.githubusercontent.com/assets/17923501/23468926/06c4ff18-fe9a-11e6-806d-fd15e5dd61e9.png)

**Comment by vpp** [comment]
Hi Asim,

Looks like an issue. I will investigate and update this ticket.

**Comment by bigheadsmith** [comment]
I have encountered the same issue. Reported it before realising I was creating a duplicate.
I have closed the duplicate issue now.

**Comment by vpp** [comment]
@bigheadsmith thank you for reporting

**Comment by GalenY** [comment]
I have just encountered the same issue. Negative adjustments won't work unless they are whole integers.

**Comment by vpp** [comment]
Thank you @GalenY for reporting.

I just pushed the fix to the master.

The cloud version will catch up later.

**Comment by vpp** [comment]
Deployed fix on timeoff.management
