### ISSUE TITLE
Can't See Remaining Allowance on Mobile

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#123]
Hi @vpp 

Another recommendation is that you can't see the remaining allowance when on a mobile device. This would be brilliant if we could allow users to see their remaining balance on mobile.

![image](https://cloud.githubusercontent.com/assets/17923501/23470017/2ecbce8a-fe9d-11e6-924c-f3e3faab5728.png)

**Comment by AsimPervez93** [comment]
I can see that the restriction is that your screen width resolution must be 768px wide to display the "top-leave-type-statistics" element.  Could we modify this to display the allowance on smaller screens?

**Comment by vpp** [comment]
@AsimPervez93, thanks for suggestion.

Done.
