### ISSUE TITLE
Consider adding holiday approvers on individual bases rather than on departments

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#13]
As one of our customers suggested:

"It would be very helpful to be able to be to assign an approver individually for each employee rather than having the approver combined with the department."

We need to think how to add this feature without having big impact on current structure of model.

Not sure about solution at this moment yet.

**Comment by vpp** [comment]
Consider adding "personal approver" field on the user, that if defined, override department's approver.

Not sure about that though. As it adds complexity to the logic of absence management.

**Comment by vpp** [comment]
As per other customer request:

> 
> 2) Instead of having Selection box for approver it will be better to
> have Check Box. this will allow to have more that one approver in
> cases where you have direct and indirect management dependencies, eg
> Head of IT, IT manager, IT staff in this scenario Head of IT should
> have permissions to approve requests.

Maybe the list of the approvers should consist of: the approver plus all superusers from within current company.

**Comment by AsimPervez93** [comment]
This would be a welcomed feature.

**Comment by vpp** [comment]
Similar to #85

**Comment by vpp** [comment]
Similar to #82

**Comment by vpp** [comment]
I am closing this issue as the work is going to be done under #82.
