### ISSUE TITLE
Adding user fails

### ISSUE THREAD

**Issue by jekuno** [timeoff-management/application#130]
Adding a new user via /users/add/ fails with flash error `"Failed to add new user"`.

The log shows `An error occurred when trying to add new user account by user 1 : SequelizeDatabaseError: invalid input syntax for integer: ""` 

Reason is that the app tries to set the column `adjustment` to `''`.
The form displayed in the UI doesn't contain any `adjustment` field.

I use PostgreSQL.

**Comment by jekuno** [comment]
Additional info:

The  `allowance` for the assigned department is set to 28. 
The default value for the `adjustment` column in my PostgreSQL database correctly is 0 and its data type is integer.

**Comment by vpp** [comment]
Thanks for reporting @jekuno

**Comment by vpp** [comment]
Fixed in master.
