### ISSUE TITLE
Mobile team view broken

### ISSUE THREAD

**Issue by jekuno** [timeoff-management/application#136]
The team view on mobile phones currently breaks the employee names and their calendar entries into separate rows/regions making it hard to associate names with calendar entries.

**Comment by vpp** [comment]
hi @jekuno, the "Team view" page was not supposed to be viewed on mobile devices as it is "hidden" for them.

Please refer to #135 for more information.

**Comment by jekuno** [comment]
Thanks for the info. As soon as the calendar team feed supports a sufficient range (IMHO best would be 1 year back and 1 year ahead, see https://github.com/timeoff-management/application/issues/128#issuecomment-290071334) one can simply integrate the "team view" into the native calendar of the mobile phone so that it indeed isn't needed in the mobile website.

**Comment by vpp** [comment]
Good argument toward idea you've mentioned in #128. Thank you @jekuno!
