### ISSUE TITLE
License

### ISSUE THREAD

**Issue by folhabranca** [timeoff-management/application#141]
Is it possible to make the License more explicit?

**Comment by mladenmilev** [comment]
@folhabranca: Can you clarify the question?  Under what license the code is distributed?

**Comment by vpp** [comment]
I was thinking about MIT.

I will update the codebase to be clear on this point.

**Comment by folhabranca** [comment]
yes, even if the timeoff.management site says it is an open source project, there is nothing regarding distribution and usage in the github repo.

**Comment by vpp** [comment]
Added license to master branch.
