### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by nnmalex** [timeoff-management/application#143]
It would be very helpful if admin user could generate a CSV report of the absences for all users for a certain period of time for HR and Accounting purposes.

**Comment by nnmalex** [comment]
Hi Pavlo,

I would think the following columns would be useful:

- Employee  name
- Department
- Absence type
- Absence duration
- Absence start date
- Absence end date
- Status

For every absence record (or for the selected one) for every employee (or for the selected one) for the selected period.

**Comment by mladenmilev** [comment]
This might be related with https://github.com/timeoff-management/application/issues/164

**Comment by vpp** [comment]
To re-evaluate this ticket as some of those requirements are done in allowance by time report
