### ISSUE TITLE
Official releases

### ISSUE THREAD

**Issue by thperret** [timeoff-management/application#149]
Hi,
We're using timeoff.management in our team and I have created a [docker image for timeoff](https://github.com/thperret/timeoff-management_docker). Could you create official releases by tagging corresponding commits? This would facilitate the image creation process.
There's also the license question #141, could you clarify that also?

Thanks for this great tool!

**Comment by vpp** [comment]
hi @thperret

Thanks for suggestion.

I am definitely need to do this.

Can you please provide some examples of other projects on GitHub how you would prefer it to be done?

**Comment by thperret** [comment]
I don't really have preferences, I would suggest to follow [github's release process](https://help.github.com/articles/creating-releases/) by just tagging commits and creating the corresponding release (and if possible signing them with a public PGP key) corresponding to version changes.

e.g.: you could tag 0.4.4 latest version change commit: `git tag -a [-s] 0.4.4 c476af3c627f2d86d4827504776cfa082af17152`

A random example of one software I use (and really like) uses github's releases: https://github.com/openpaperwork/paperwork/releases

**Comment by vpp** [comment]
Thank you, @thperret!

**Comment by vpp** [comment]
@thperret, I started to use GitHub releases workflow. 

Please check https://github.com/timeoff-management/application/releases

Lets see how it goes.

**Comment by vpp** [comment]
Closing this issue.
