### ISSUE TITLE
Team view for long department names

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#152]
As per feedback:

> When department name is long (example “Operations – Global Sales – Africa region” or  “R&D – Project X – Team A“  ), in teams calendar view, the drop box is overlapping with the calendar when the screen resolution is 1600 x 900 on laptop PC

**Comment by mladenmilev** [comment]
Simple solution to overcome this problem is to reorganize components like this

**Comment by mladenmilev** [comment]
https://github.com/mladenmilev/timeoff/commit/82d03e55e7db42aa51bbc956b3d9f2e7b3bf1620

**Comment by vpp** [comment]
Fixed.
