### ISSUE TITLE
Export of user list as .CSV

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#164]
As per feedback:

> In the Staff screen add a column per user showing the remaining days
> to take off. And that is really important. 
> 
> Good option will be to have "export" to CSV for this table - Name,
> Department, Used days, Available Days. That is something values by
> Human Resources and Finance as available days are relevant for the
> financial sheets of a company!

**Comment by mladenmilev** [comment]
I suggested CSV as it is simple text file with "," or ";" as separator. 
I see there are also Excel libs for exporting. Check this one which looks simple and has example how to create the excel in the memry buffer and directly stream it for download
https://www.npmjs.com/package/node-excel-export

**Comment by mladenmilev** [comment]
consider also https://github.com/timeoff-management/application/issues/143

**Comment by vpp** [comment]
Done
