### ISSUE TITLE
Issues with LDAP auth

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#174]
hey, im having trouble with the LDAP setup.  I fed in our info (server, pass, binddn and search base), but when i put in my email auth pass, its saying that the password is invalid.  our information is like this:
server: ldap://X.X.X.X:X
binddn: CN=ldap.auth,DC=XXX,DC=local
searchbase: DC=XXXX,DC=local

Is there anything i'm missing?  Usually we log into active directory with firstname.lastname and password.

**Comment by vpp** [comment]
We need to know if "Enable LDAP authentication" flag was turned on on the account.

**Comment by jessewallace** [comment]
It was; we did figure it out.  In our case, it was a local LDAP, and we had to pass in credentials a certain way.

The BindDN had to be domain\ldap.auth
It took lots of tinkering to figure that out :)

Thanks for the response, hopefully this helps someone!

**Comment by vpp** [comment]
Thank you @jessewallace for reporting the fix.
