### ISSUE TITLE
Request Dates do not match Requested Dates

### ISSUE THREAD

**Issue by SmoresGuy** [timeoff-management/application#175]
Steps to Reproduce

1. Click Add Request
2. Enter request for Employee with Desired Date
3.  Click Create
4. Review Requests

Expect Result: Request should be showing with Dates requested by the employee on request.
Actual Result: Request is showing request on day _Earlier_ than the actual request.
![image](https://user-images.githubusercontent.com/13749952/27343644-8751f1ae-55b1-11e7-872a-f4f7327281bf.png)
![image](https://user-images.githubusercontent.com/13749952/27343690-ad4d08a8-55b1-11e7-89c5-358c025a60f7.png)

**Comment by vpp** [comment]
hi @SmoresGuy 

thank you for reporting, I suspect you are in very different time zone then Europe.

The issue should be fixed after #58 ticket is fixed.

**Comment by SmoresGuy** [comment]
@vpp You are correct, I am in Canada, specifically Eastern Time Zone.

**Comment by vpp** [comment]
As workaround you can set the time of the machine that runs the app to. E either UTC or GMT (it it is convenient). Although there will be some issues when you open the app at the point that in Europe it is next day but Canada is still on current one.

**Comment by jekuno** [comment]
Probably a related bug:

After adding a leave request for 2017-09-01 I cannot add another leave request for 2017-08-31.
The (wrong) error message is: "Failed to create a leave request. Overlapping booking!"

Timezone Berlin / Europe.

**Comment by vpp** [comment]
hi @jekuno this bug should not manifest itself in Europe's timezones.

Are you sure that new failing leave request is not overlaps with any other leaves? Maybe the other one is not approved yet? Or maybe it has halfs?

For instance what does this query returns for the database:

select id, status, userId, date_start, date_end, day_part_start, day_part_end  from leaves where date_start  > '2017-08-20' and date_end < '2017-09-05';

**Comment by jekuno** [comment]
It returns one row with: 
`37;1;2;"2017-09-01 00:00:00+00";"2017-09-01 00:00:00+00";1;1`

**Comment by vpp** [comment]
@jekuno, I failed to reproduce issue, but after looking around code at https://github.com/timeoff-management/application/blob/master/lib/model/mixin/user/absence_aware.js#L127 it is indeed very likely that this is a manifestation of current issue (assuming your server is in Berlin's time zone, actually you pointed it above).

The timezones issue is next I am going to pick up. There is a brach where it is almost done https://github.com/timeoff-management/application/commits/YulioTech-bug-fix-timezone-logic created based on @gerrypower 's pull request.

As a work around you could set server's timezone to be UTC, or if the server is shared by other apps you can just remove the holiday for 1st Sep and add new one for 31 Aug - 1 Sep.

**Comment by jekuno** [comment]
Creating a leave from 31 Aug - 1 Sep unfortunately is no option as the two timeoffs have different leave types. As I don't have access to the server config I'll wait for your release then.

Thanks for investigating this issue.

**Comment by vpp** [comment]
Should be fixed now as part of #58
