### ISSUE TITLE
Can't Export Company Data

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#179]
Hi @vpp 

I'm having an issue where when trying to Export company data (I wan't to move the instance of timeoff to a different linux machine) I'm getting a 504 error.

Exporting:
![image](https://user-images.githubusercontent.com/17923501/29616384-39d43e02-8809-11e7-892d-d5b0a0493a2d.png)

Error:
![image](https://user-images.githubusercontent.com/17923501/29616393-42d267cc-8809-11e7-9fa1-f02b3699bdd4.png)

Here's an excerpt from terminal at the time of exporting:
```
<--- Last few GCs --->

 2685665 ms: Mark-sweep 1391.7 (1434.6) -> 1391.7 (1434.6) MB, 1061.0 / 0.0 ms [allocation failure] [scavenge might not succeed].
 2686675 ms: Mark-sweep 1391.7 (1434.6) -> 1391.7 (1434.6) MB, 1009.9 / 0.0 ms [allocation failure] [scavenge might not succeed].
 2687791 ms: Mark-sweep 1391.7 (1434.6) -> 1394.5 (1418.6) MB, 1115.6 / 0.0 ms [last resort gc].
 2688733 ms: Mark-sweep 1394.5 (1418.6) -> 1397.2 (1418.6) MB, 942.3 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x10d3f9c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape, v8::internal::Handle<v8::internal::Name> >::New(v8::internal::Isolate*, int, v8::internal::MinimumCapacity, v8::internal::PretenureFlag) [node]
 7: v8::internal::Dictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape, v8::internal::Handle<v8::internal::Name> >::EnsureCapacity(v8::internal::Handle<v8::internal::NameDictionary>, int, v8::internal::Handle<v8::internal::Name>) [node]
 8: v8::internal::Dictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape, v8::internal::Handle<v8::internal::Name> >::Add(v8::internal::Handle<v8::internal::NameDictionary>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails) [node]
 9: v8::internal::JSObject::AddSlowProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) [node]
10: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [node]
11: v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode, v8::internal::Object::StoreFromKeyed) [node]
12: v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [node]
13: v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>) [node]
14: node_sqlite3::Statement::RowToJS(std::vector<node_sqlite3::Values::Field*, std::allocator<node_sqlite3::Values::Field*> >*) [/var/www/html/application/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node]
15: node_sqlite3::Statement::Work_AfterAll(uv_work_s*) [/var/www/html/application/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node]
16: 0x1371585 [node]
17: 0x137356c [node]
18: 0x1373663 [node]
19: 0x13845a8 [node]
20: uv_run [node]
21: node::Start(int, char**) [node]
22: __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
23: _start [node]
Aborted (core dumped)

npm ERR! Linux 4.4.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! jswebapp@0.0.0 start: `node bin/wwww`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the jswebapp@0.0.0 start script 'node bin/wwww'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jswebapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/wwww
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jswebapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jswebapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/application/npm-debug.log
```

**Comment by vpp** [comment]
Hi @AsimPervez93 

Thank you for reporting, I will have a look soon.

**Comment by AsimPervez93** [comment]
Hi @vpp 

Has there been any movement on this issue?

I'm really wanting to migrate Timeoff from our local server to AWS and I'd need to export and import to do that.

Hope to hear from you soon.
Asim

**Comment by vpp** [comment]
hi @AsimPervez93 sorry was busy with other stuff.

I will have a look for you this week, hopefully it is not big deal as I suspect the issue is that import logic is not aware of recent schema changes.

**Comment by AsimPervez93** [comment]
@vpp 

No problem at all!  Hopefully shouldn't be too difficult.  Looking at the above excerpt, I initially thought it was a memory issue but I'm not too sure.  Hopefully your suspicion is correct.

**Comment by vpp** [comment]
hi @AsimPervez93 

I just checked current version and it looks OK to export company details to another installation. There are some minor missing entities like email audit and schedule, but apart from this the export should be fine.

Very likely that as per  your suggestion in your case it just happened that process does not have enough memory to build the JSON file. 

Maybe it is worth trying to export the account just after application restart?

Or if you using SQLite as database then migration should be just a matter of moving the db file to new location.

**Comment by AsimPervez93** [comment]
@vpp 
I got a similar out of memory error when I tried after closing and restarting the application. I don't imagine my application is up to date, would it be possible to move the db file to a newer version?

**Comment by vpp** [comment]
hi @AsimPervez93, moving DB file should do the trick.

* do fresh checkout from master on new place
* copy DB file over to new place
* copy config file over to new place (if you updated default values)
* on new place "npm install"
* on new place "npm run-script db-update"
* and then finally "npm start"

The steps above should do the job.

**Comment by AsimPervez93** [comment]
@vpp 
It looks like I'm going to have to do that.  May be a dumb question but where is the db saved?

**Comment by vpp** [comment]
If you use default settings there should be file "db.development.sqlite" in the root of checkout

**Comment by AsimPervez93** [comment]
Found it.

I'll give this a go and post another comment once It's done.  Might be early next week-ish.

Thanks @vpp

**Comment by yusong555** [comment]
This migration process worked for me. 

the only catch is that old users' password did not work, but once have done password reset. everything works.  :)

many thanks.
