### ISSUE TITLE
Month absence summary for each employee

### ISSUE THREAD

**Issue by HonzaTuron** [timeoff-management/application#184]
Hey @vpp and thank you for your great app!

I'm looking for month summary of absences (for each leave type) for each employee. Is this functionality somewhere available or it needed to be implemented?

I have a vision about this sort of informations in team view:
![image](https://user-images.githubusercontent.com/20155254/30540523-d1d9f340-9c77-11e7-914f-74579f9857d5.png)
E.g. somewhere between name and dates

Thank you!

**Comment by petrvecera** [comment]
This is quite critical feature for us (our accountant). If it's not anywhere we will implement it and add PR ;-)

**Comment by AsimPervez93** [comment]
I can third this.

**Comment by theapprover** [comment]
I support this request.

**Comment by petrvecera** [comment]
FYI Started working on it today.

**Comment by petrvecera** [comment]
Ok guys, so this is what I got: 
![image](https://user-images.githubusercontent.com/8086995/32254081-e1c8dcb4-be9e-11e7-9064-58b9ccd50ab3.png)

But I don't know what to do when there is more types of leaves, how to handle that 😕

**Comment by vpp** [comment]
@petrvecera looks good to me.

Maybe the column to show only how many days were used, and when one mouse over on it it shows pop over with more details https://getbootstrap.com/docs/3.3/javascript/#popovers-examples

That way the main page will not be affected by dynamic nature of leave types

**Comment by petrvecera** [comment]
Overview:
![image](https://user-images.githubusercontent.com/8086995/32302773-c49d782c-bf64-11e7-8ae3-b330f3cda71a.png)

Detail for one user:
![image](https://user-images.githubusercontent.com/8086995/32302788-cf709c3e-bf64-11e7-84e1-f0a6372c4e89.png)

Full summary:
![image](https://user-images.githubusercontent.com/8086995/32302802-e454062c-bf64-11e7-963a-d5b7840923bf.png)
Also we could have EXPORT button in here :)

**Comment by vpp** [comment]
@petrvecera this looks great!

**Comment by theapprover** [comment]
This does look great, any advise or guidance for implementation?

**Comment by petrvecera** [comment]
@theapprover  I made PR https://github.com/timeoff-management/application/pull/192, I hope we can work together with @vpp and bring it to the master. But if you want you can pick it up here https://github.com/petrvecera/application/tree/team_view_absence_summary

**Comment by vpp** [comment]
@petrvecera thank you for PR.

I will have a look properly at it very soon

**Comment by vpp** [comment]
The original feature was added as part of https://github.com/timeoff-management/application/releases/tag/v0.8.0 release.

@petrvecera thank you for participating.
