### ISSUE TITLE
SMTP setting not working

### ISSUE THREAD

**Issue by cprashant1** [timeoff-management/application#189]
I tries our company SMTP detail mail not worked . I tried Gmail SMTP still it is not working
I am getting the error Failed to create a leave request. where can i see complete logs ?
I am using below settings 

"allow_create_new_accounts" : false,
  "send_emails"              : true,
  "application_sender_email" : "My Mail",
  "email_transporter" : {
    "host" : "smtp.gmail.com",
    "port" : 465,	
    "auth" : {
      "user" : "My Mail",
      "pass" : "Pass"
    }
  },
  "crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_",
  "application_domain" : "http://app.timeoff.management",
  "promotion_website_domain" : "http://timeoff.management"

**Comment by HyperSquiZ** [comment]
I had to add an extra line to tell nodemailer to use ssl.  Also if your email account is using two factor you will have to create an app password to use, or if its not using two factor you need to enable "less secure apps" (https://myaccount.google.com/lesssecureapps)

"allow_create_new_accounts" : false,
"send_emails" : true,
"application_sender_email" : "My Mail",
"email_transporter" : {
"host" : "smtp.gmail.com",
"port" : 465,
**"secure" : true,**
"auth" : {
"user" : "My Mail",
"pass" : "Pass"
}
},
"crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_",
"application_domain" : "http://app.timeoff.management",
"promotion_website_domain" : "http://timeoff.management"

**Comment by vpp** [comment]
@HyperSquiZ, thank you for sharing about email settings.

@cprashant1 hope the above suggestion works for your setup.

**Comment by cprashant1** [comment]
Thanks , can you tell me where can i see logs for any failure ? also i want to work with our company's Outlook 365 

{
  "allow_create_new_accounts" : true,
  "send_emails"              : true,
  "application_sender_email" : "Timeoff@test.com",
  "email_transporter" : {
    "host" : "outlook.office365.com",
    "port" : 587,
	"secure" : true,
	"ignoreTLS": false,
    "auth" : {
      "user" : "Timeoff@test.com",
      "pass" : "My_Pass"
    }
  },
  "crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_",
  "application_domain" : "http://app.timeoff.management",
  "promotion_website_domain" : "http://timeoff.management"
}

**Comment by vpp** [comment]
With default settings they just go to STDOUT, so if you "npm start" from your console app would just keep spiting log messages into that terminal session. If you want to herd those messages into files you have to redirect the STDOUT and STDERR into those files. E.g. `node bin/wwww_cluster >> /log_dir_path/log/all.log  2>&1`

**Comment by cprashant1** [comment]
Thanks it worked with Gmail. but i am still facing issue with our company's office 365 account

I turned on TLS flag to true since 587 is TLS port but still it doent work , any idea ?
{
"allow_create_new_accounts" : true,
"send_emails" : true,
"application_sender_email" : "Timeoff@test.com",
"email_transporter" : {
"host" : "outlook.office365.com",
"port" : 587,
"secure" : true,
"ignoreTLS": false,
"auth" : {
"user" : "Timeoff@test.com",
"pass" : "My_Pass"
}
},
"crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_",
"application_domain" : "http://app.timeoff.management",
"promotion_website_domain" : "http://timeoff.management"
}

**Comment by HyperSquiZ** [comment]
I believe the secure option is only true for port 465.  If using port 587 I think you need "secure" false.

**Comment by HyperSquiZ** [comment]
Try setting secure option to false.

"secure – if true the connection will use TLS when connecting to server. If false (the default) then TLS is used if server supports the STARTTLS extension. In most cases set this value to true if you are connecting to port 465. **For port 587 or 25 keep it false**" - https://nodemailer.com/smtp/

**Comment by cprashant1** [comment]
even after secure false and using TLS port still not working

{
  "allow_create_new_accounts" : false,
  "send_emails"              : true,
  "application_sender_email" : "testmail",
  "email_transporter" : {
"host" : "smtp.office365.com",
"port" : 587,
"secure" : false,
"auth" : {
"user" : "testmail",
"pass" : "pass"
}
  },
  "crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_",
  "application_domain" : "http://skuawinserv1:3000",
  "promotion_website_domain" : "http://skuawinserv1:3000"
}

**Comment by HyperSquiZ** [comment]
try the below.  I've seen some posts about having to specify SSLv3 for Office365 SMTP.

{
"allow_create_new_accounts" : false,
"send_emails" : true,
"application_sender_email" : "testmail",
"secure" : false,
"email_transporter" : {
"host" : "smtp.office365.com",
"port" : 587,
"tls" : { "ciphers" : "SSLv3" },
"auth" : {
"user" : "testmail",
"pass" : "pass"
}
},
"crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_",
"application_domain" : "http://skuawinserv1:3000",
"promotion_website_domain" : "http://skuawinserv1:3000"
}

**Comment by vpp** [comment]
@cprashant1, there was similar issue few months ago, please have a look at the thread: https://github.com/timeoff-management/application/issues/142#issuecomment-293970765

**Comment by cprashant1** [comment]
Itried below but no luck , not sure what extra paramater office365 expecting . I also tried with "ignoreTLS": false , still it doesnt work.
{
  "allow_create_new_accounts" : false,
  "send_emails"              : true,
  "application_sender_email" : "mail",
  "email_transporter" : {
"host" : "smtp.office365.com",
"port" : 587,
"secure" : false,
"tls" : { "ciphers" : "SSLv3" },
"auth" : {
"user" : "myemail",
"pass" : "pass"
}
  },
  "crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_",
  "application_domain" : "http://web:3000",
  "promotion_website_domain" : "http://web:3000"
}

**Comment by vpp** [comment]
Not sure it is possible to find the solution for this issue without access to the environment where it manifests itself.

**Comment by b0n0** [comment]
Hi, use
 "auth" : null
and it works
{
  "allow_create_new_accounts" : false,
  "send_emails"              : true,
  "application_sender_email" : "TimeOFF.Request <TimeOFF@xxx>",
  "email_transporter" : {
    "type" : "smtp",
    "host" : "xxxx",
    "port" : 25,
    "secure" : false,
    "ignoreTLS" : false,
    "tls": {
    "rejectUnauthorized": false
    },
    "auth" : null
