### ISSUE TITLE
Other users details

### ISSUE THREAD

**Issue by gyandal** [timeoff-management/application#196]
When we have set our instance running and added several users.

Once those users start logging in, 'sessions' seem to leak between logged in users.

I can be using the application, click back to calendar and be shown the calendar details of another user, the access writes for that user seem to be present, i.e if I have access to employees but the other user does not, once the session leak occurs, I 'lose' access to employees.  When I regain my session I have the access back.

This seems to occur if I am already logged in and some other user logs in since then.

**Comment by vpp** [comment]
hi @gyandal 

Interesting issue.

Is it possible to get more precise scenario how to reproduce the problem, something like:

1) in Chrome browser login as user A into account and opne team view page 
2) in Firefox browser login as user B and open requests page
3) as user A in Chrome go to calendar page and observe that it is user B's calendar instead of user A's

That way it would be much easier to reproduce the issue as I cannot observe that on my installation.

**Comment by gyandal** [comment]
Thanks for the quite reply.
I will certainly try to re-create this issue on one machine.
We seem to be able to reliably re-create the issue where by I log in on my
machine.

Whilst logged in another user logs in on their machine.

If I refresh /calendar I will likely get the latest users details present.

**Comment by vpp** [comment]
May be on those different machines you use lets say Chrome that is logged to the same Google account? And chrome tries to be wise and use the latest cookies key with timeoff.management?

Like it does with remembering passwords etc

(I do not have two machines in hand at this moment to check this hypothesis)

**Comment by gyandal** [comment]
I have managed to re-create this locally

I have attached a video file I hope you can play back.

On the left is Chrome, on the right is Firefox.

I was expecting to log into chrome and see my calendar.

I was expecting to then log into firefox and see Andrew's calendar, I would
then refresh chrome to see my(Stephen's) calendar change to Andrew's.

However I actually logged in on firefox(Andrew) and saw Stephen's calendar
immediately.

After a few log ins and out I was able to log in as Andrew and see Andrew's
calendar, there after Stephen logged in on Chrome saw Andrew's calendar.

**Comment by vpp** [comment]
@gyandal unfortunately github does not store attachements, can you please send it to pavlo@timeoff.management

**Comment by vpp** [comment]
@gyandal can you please also send me versions of node and nvm you use ("node -v" and "npm -v") and platform you run the app on Linux distro, Windows etc

**Comment by gyandal** [comment]
I have sent the recording, I will find out the details you have asked for asap


Sent from my Cyanogen phone


On 8 Nov 2017 5:35 pm, Pavlo <notifications@github.com> wrote:

@gyandal can you please also send me versions of node and nvm you use ("node -v" and "npm -v") and platform you run the app on Linux distro, Windows etc

**Comment by gyandal** [comment]
Node version is 6.11.5
and npm version is 3.10.10

**Comment by gyandal** [comment]
Looking at the node.js website I see we're a few versions behind.I've
update to the latest stable lts 8.9.1.

The issue is still present.

**Comment by vpp** [comment]
@gyandal really weird..

Which operation system you use with the app?

I assume you use defaul settings with SQLite as DB.

When you open any page by one browser and then by another can you check log file for statement like this:

Executing (default): UPDATE `Sessions` SET `expires`='2017-11-10 13:27:29.821 +00:00',`updatedAt`='2017-11-09 13:27:29.822 +00:00' WHERE `sid` = '9MjhKLqXWidv942IigjZkRD9Hv26nHkC'

Does "sid" is unique per each browser in you case?

(I am failing to reproduce the issue in my environment so have to ask those questions)

**Comment by gyandal** [comment]
It is currently running on a Windows Server 2012 server.
Yes no other settings or configuration used with SQLite.  I'll monitor the log.  I'll try and record the log also.

**Comment by vpp** [comment]
In fact looks like the TimeOff.Management app is not ready for cutting edge node version as there are lots of errors when installing dependencies.

I would suggest to use v4.8.3 for instance.

Consider using nvm to have different node versions: https://github.com/creationix/nvm

**Comment by gyandal** [comment]
From the log I can see one sid for one user, another sid for the other user.

However, despite two different sids both browsers display data for the same user.

**Comment by gyandal** [comment]
"In fact looks like the TimeOff.Management app is not ready for cutting edge node version as there are lots of errors when installing dependencies.

I would suggest to use v4.8.3 for instance.

Consider using nvm to have different node versions: https://github.com/creationix/nvm"

I deleted the node-modules folder and performed npm install and that seemed to install without error or issue.  However I can try an older version if you believe this to be the cause of this issue.*

*As previously mentioned my node version was 6.11.5.

**Comment by gyandal** [comment]
After some digging I believe to have found the issue.

We are using iis to route our request on https://x.y.z  to port 3000 the application is running on.
IIS was caching the output.
 I had to disable both of these settings
![image](https://user-images.githubusercontent.com/912406/32649633-ac9f620a-c5f2-11e7-87ef-680e4e98ebea.png)

Thanks for all your efforts.

Hopefully this will help anyone else with a similar issue :-)

**Comment by vpp** [comment]
Hi @gyandal, thank you for sharing. It is indeed very useful.

**Comment by gazben** [comment]
This is a problem in apache2 too.
Solution:
```   
<Location / >
     ExpiresActive On
     ExpiresDefault "now"
</Location>
```
