### ISSUE TITLE
How to approve leave request when manager is not available?

### ISSUE THREAD

**Issue by petrvecera** [timeoff-management/application#202]
What to do when manager is not available and people from his department have leave requests? 

I can't find a way for admin to be able to simply approve those.  Is there any option for it? 

Thank you

**Comment by vpp** [comment]
Hi Petr,

Current master has a new feature of secondary approvers that allows departments to have more then one supervisor. Although there are few rough edges to be fixed (like sending notification emails to all approvers) it does the job.

**Comment by petrvecera** [comment]
Excellent, thanks will check it out and let you know.

Just one thing
>like sending notification emails to all approvers

This should be definitely an optional :) Don't want to spam our higher management with emails.

**Comment by vpp** [comment]
There was a ticket somewhere to make emails optional. I do not have access to desktop to find a reference but I am sure issue of spamming was already raised. It was in context that not all emails have to be sent.

**Comment by petrvecera** [comment]
This was implemented in https://github.com/timeoff-management/application/commit/03dc42584be0ebac36cf02abf642352c698f2405 , looks really nice and works fine too! 👍
