### ISSUE TITLE
Instructions - Deployment to Production

### ISSUE THREAD

**Issue by helixaros** [timeoff-management/application#215]
Could someone please give us the generic instructions on how to deploy the application to a production server?

**Comment by vpp** [comment]
Hi @helixaros,

Steps listed here should be sufficient for reasonably size organisation:

https://github.com/timeoff-management/application/blob/master/README.md#self-hosting

Then keep updating installation with this steps:

https://github.com/timeoff-management/application/blob/master/README.md#updating-existing-instance-with-new-code

By default you would use SQLite database, so just keep regular backup of DB file.

Hope it helps

**Comment by helixaros** [comment]
Thank you @vpp for the prompt reply!

Does that mean, that I would need to constantly have the terminal open (which will be running the server) as well as the only way for users to access the applications is through the use of localhost:3000 instead of a custom domain?

**Comment by vpp** [comment]
Ah I see.

The instructions on readme are how to start the application.

How to incorporate it into existing infrastructure vary and depend on given case. Based on your company infrastructure or web hosting you are going to use.

For instance in case of https://app.timeoff.management the app is started with the same instructions as in readme, but webhosting infrastructure is configured to redirect all requests to the domain of https://app.timeoff.management to be piped into the application.

In simple case, given you want to deploy the app on internal infrastructure, you would need:

- find machine which is constantly online in you local network, lets say it will be shared.mycompany.local
- start the timeoff app as a deamon, one way is https://stackoverflow.com/a/4018223
(by default it would listen on port 3000)
- configure webserver that handles requests to shared.mycompany.local to have lats say timeoff.shared.mycompany.local to point to deamon app you started above (do not forget default port 3000)

Anyway it is best to talk to someone who maintains the infrastructure in your organisation.

BTW, there is an option to use the application as cloud service. The would be hustle free: with all updates and backups done for you. And the price is really small.

Hope it helps

**Comment by helixaros** [comment]
Thank you so much!
