### ISSUE TITLE
12/31/18 not showing leave on calendar

### ISSUE THREAD

**Issue by shellhouse** [timeoff-management/application#219]
Leave for 12/31/18 does not show on calendar views.  The date is not colorized for the employees with leave requests.

**Comment by vpp** [comment]
Indeed it it is not there.

@shellhouse thank you for reporting

**Comment by vpp** [comment]
It is something about case when holiday is one day and it is very last day of the year.

It happens for 2019 year as well.

if it is more then one day it shows up OK.

**Comment by vpp** [comment]
This happens because query to get all leaves for year has condition

BETWEEN '2018-01-01' AND '2018-12-31'

Dates need to be more detailed, like '2018-12-31 00:00:00.000 +00:00'

**Comment by vpp** [comment]
Fix is in the master.
