### ISSUE TITLE
Slow processing when sending emails?

### ISSUE THREAD

**Issue by thomasgreen** [timeoff-management/application#220]
I've managed to configure the emails to send from my SMTP server yet when doing so it can to way to long for the site to become interactive again. It took 16 seconds to delete and request a a holiday.

Watching the console log in the terminal it appears to be a long pause just before "Executing (default): INSERT INTO `EmailAudit..." appears.

Is this a known problem? Have I missed some setting?

**Comment by vpp** [comment]
Looks like there is a slow communication link between application instance and SMTP server.

**Comment by thomasgreen** [comment]
I'm still testing it out on my localhost currently. Not sure if that is an issue but I'll try it when I set it up on a server and see if that allows for a faster connection.
