### ISSUE TITLE
Holiday Allowance per User

### ISSUE THREAD

**Issue by kamilkosek** [timeoff-management/application#221]
Hi,
i dont know if its already possible:
In our company it is usual to have a different number of holidays per user, even if in the same team. It depends on what you negotiated with the boss ;)
So my question is, is it possible to give specific user a specific amount holidays?

**Comment by vpp** [comment]
Hi,

Yes, just set the allowance for department to be zero and then adjust holidays on individual base by using "allowance adjustment" field.

Thanks
Pavlo

**Comment by kamilkosek** [comment]
Thanks for the fast response :)
