### ISSUE TITLE
Retire feature of data migration between instances

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#229]
Looks like the feature of data migrations between installations is not popular with users, so I am going to retire it.

Customers of cloud hosting do not care about it. Users who host solution on their infrastructure are doing it by migrating underlying database.

**Comment by ignaciolflores** [comment]
How will be able to export data a cloud user?

**Comment by vpp** [comment]
What I was thinking about is to: retire the whole account migration and replace it with ability to download users and their leaves in .CSV format.

So customers still can get their data in readable format if they wish. Although they will not be able to move that data to new instancne of TimeOff.Management.

**Comment by ignaciolflores** [comment]
We are cloud customers, and having the opportunity to migrate to our own instance is a good feature. Maybe we don't make it never, but having the opportunity is great and give us freedom, that is one thing companies really appreciate.

**Comment by vpp** [comment]
@ignaciolflores thank you for feedback about this feature
