### ISSUE TITLE
GET /favicon.ico 404

### ISSUE THREAD

**Issue by marct83** [timeoff-management/application#247]
Another error in the log. This doesnt cause a crash I'm just curious what is happening.

Executing (default): UPDATE "Sessions" SET "expires"='2018-02-13 16:37:04.417 +00:00',"updatedAt"='2018-02-12 16:37:04.418 +00:00' WHERE "sid" = '9ApixaVmY-ImG7CY_PDSHYKlZyZjJr_W'
GET /favicon.ico 404 20.834 ms - 1192

**Comment by vpp** [comment]
One needs to put favicon.ico to the app

**Comment by vpp** [comment]
Should be fixed now
