### ISSUE TITLE
Set passwords for bulk user import

### ISSUE THREAD

**Issue by Timmmm** [timeoff-management/application#256]
With the bulk user import option (from CSV) the password is always set to `undefined` (classic Javascript! I had to read the source to learn this).

Suggested solution:

1. Default password should be blank, not `undefined` (check for `=== undefined`).
2. Add a `password` field to the CSV - in the downloaded sample they should be blank.

**Comment by vpp** [comment]
@Timmmm thank you for reporting.

**Comment by vpp** [comment]
Fixed.
