### ISSUE TITLE
Can't get app installed

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#274]
Hi  @vpp, it's been a while!

I'm trying to install the app on a new server to do some testing but I'm having issue after issue.

Firstly, after doing `npm install`, node-sass would not install so I managed to use `npm install -f node-sass` to get that to install.

Now, when i do `npm start` I get the below error that I'm not sure what to do with, can anyone help?
![image](https://user-images.githubusercontent.com/17923501/39121345-43a8d16e-46e9-11e8-8459-9a224d71d764.png)

**Comment by vpp** [comment]
To me it looks like "node" is not pointing to node.js what "which node" gives you back?

**Comment by AsimPervez93** [comment]
huh that's strange.  `which node` gives back nothing

**Comment by AsimPervez93** [comment]
which `nodejs` returns` /usr/bin/nodejs`

**Comment by AsimPervez93** [comment]
Okay so building off your premise that node is messed up, I purged nodejs and installed it using 

```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```
This gets me a little further,` which node` now returns `/usr/bin/node`

I now get this error when running `npm start`

```
asim@ubuntu:/var/www/html/anleave$ sudo npm start

> TimeOff.Management@0.10.0 start /var/www/html/anleave
> node bin/wwww

/var/www/html/anleave/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25
      throw new Error('Please install sqlite3 package manually');
      ^

Error: Please install sqlite3 package manually
    at new ConnectionManager (/var/www/html/anleave/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:25:13)
    at new SqliteDialect (/var/www/html/anleave/node_modules/sequelize/lib/dialects/sqlite/index.js:12:28)
    at new Sequelize (/var/www/html/anleave/node_modules/sequelize/lib/sequelize.js:233:18)
    at Object.<anonymous> (/var/www/html/anleave/lib/model/db/index.js:8:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/anleave/app.js:25:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/anleave/bin/wwww:4:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TimeOff.Management@0.10.0 start: `node bin/wwww`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TimeOff.Management@0.10.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asim/.npm/_logs/2018-04-23T11_23_54_921Z-debug.log

```

**Comment by AsimPervez93** [comment]
to fix this error `Error: Please install sqlite3 package manually` I purged sqlite3 and then used `npm install sqlite3 --save` and now the app works.

**Comment by vpp** [comment]
AsimPervez93, thank you for sharing

**Comment by santosgabriel** [comment]
@AsimPervez93 thanks, this solution works fine for Windows based NodeJS.

**Comment by chenyu9312** [comment]
I am having the same issue after I update my node from 8x version to 10x

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle TimeOff.Management@0.10.0~prestart: TimeOff.Management@0.10.0
6 info lifecycle TimeOff.Management@0.10.0~start: TimeOff.Management@0.10.0
7 verbose lifecycle TimeOff.Management@0.10.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle TimeOff.Management@0.10.0~start: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Chenyu\Desktop\TimeOff\timeoff-management\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\Chenyu\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Users\Chenyu\AppData\Local\Programs\Python\Python37-32\;C:\Users\Chenyu\AppData\Local\Programs\Python\Python37-32\DLLs\;C:\Users\Chenyu\AppData\Local\Programs\Python\Python37-32\Lib\;C:\Users\Chenyu\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\sqlite;C:\Program Files (x86)\nodejs\;C:\Users\Chenyu\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\tabcmd;C:\Users\Chenyu\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Users\Chenyu\.dotnet\tools;C:\Users\Chenyu\AppData\Local\Microsoft\WindowsApps;C:\Users\Chenyu\AppData\Local\Yarn\bin;C:\Users\Chenyu\AppData\Roaming\npm;C:\fp\swdir
9 verbose lifecycle TimeOff.Management@0.10.0~start: CWD: C:\Users\Chenyu\Desktop\TimeOff\timeoff-management
10 silly lifecycle TimeOff.Management@0.10.0~start: Args: [ '/d /s /c', 'node bin/wwww' ]
11 silly lifecycle TimeOff.Management@0.10.0~start: Returned: code: 1  signal: null
12 info lifecycle TimeOff.Management@0.10.0~start: Failed to exec start script
13 verbose stack Error: TimeOff.Management@0.10.0 start: `node bin/wwww`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid TimeOff.Management@0.10.0
15 verbose cwd C:\Users\Chenyu\Desktop\TimeOff\timeoff-management
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error TimeOff.Management@0.10.0 start: `node bin/wwww`
22 error Exit status 1
23 error Failed at the TimeOff.Management@0.10.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
