### ISSUE TITLE
MySQL foreign key error

### ISSUE THREAD

**Issue by APMarte** [timeoff-management/application#284]
Hi, 
like @enriquetoledano reported on issue #204 mysql has a problem with foreign key constraint. 
In the same issue @genietto84 shown one possible solution:

>  check on the MySql and the error is:
> 
> Error in foreign key constraint of table timeoff/departmentsupervisor:
> FOREIGN KEY (department_id) REFERENCES Department (id) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB:
> You have defined a SET NULL condition though some of the
> columns are defined as NOT NULL.
> 
> I made this change on lib/model/db/department.js on line 73
> 
> foreignKey : 'department_id',
> 
> Become:
> 
> foreignKey : {name: 'department_id', allowNull: false},
> 
> And seem to work fine.

Are you willing to accept a PR?

**Comment by vpp** [comment]
Yes, please
