### ISSUE TITLE
Timezone test "Ensure that today_usa is one day behind the today_aus" will fail during a 4 hour period.

### ISSUE THREAD

**Issue by wulfboy-95** [timeoff-management/application#310]
https://github.com/timeoff-management/application/blob/8288c20599e39ad837b0bbc54ea74e8e127be7b9/t/integration/timezone.js#L201

Both Alaska and Auckland share a 4 hour period of time in the same day which is between 8:00AM GMT and 12:00PM GMT. The test will fail during this period as it will be the same day in both time zones.

**Comment by vpp** [comment]
Yeah... It is known issue.. :) If anyone finds time zones that do not overlap lets change the test
