### ISSUE TITLE
Moving to MySQL

### ISSUE THREAD

**Issue by warren-r** [timeoff-management/application#320]
getting the following error:
Unhandled rejection SequelizeDatabaseError: ER_BLOB_CANT_HAVE_DEFAULT: BLOB, TEXT, GEOMETRY or JSON column 'timezone' can't have a default value
Any thoughts?

**Comment by warren-r** [comment]
Fixed by following change:
timezone : {
      type         : DataTypes.TEXT,
      allowNull    : true,
      defaultValue : '',
      comment      : 'Timezone current company is located in',
    },
in file company.js

**Comment by bk138** [comment]
Shouldn't this get added to the code?
