### ISSUE TITLE
carried_over_allowance doesn't discount leaves for past years

### ISSUE THREAD

**Issue by marcos-muino-garcia** [timeoff-management/application#321]
If you try to run calculate_carry_over_allowance_for_all_users.js with years 2018 & 2019, but current date is 2019, the retrieved leaves to be discounted from 2018 allowance, are retrieved for the current year.

Is an args issue in that script, as the year args is not being passed properly

**Comment by vpp** [comment]
The script uses hardcoded years 2018 -> 2019 and should work regardless current date..

https://github.com/timeoff-management/application/blob/master/bin/calculate_carry_over_allowance_for_all_users.js

Thanks
Pavlo

**Comment by marcos-muino-garcia** [comment]
Sorry about a bad explanation.

The problem is this line:

.then(() => user.reload_with_leave_details({YEAR_FROM}))
Should be to pass year from as arg:

.then(() => user.reload_with_leave_details({year:moment.utc(YEAR_FROM, 'YYYY
')}))

Thanks!

**Comment by vpp** [comment]
@marcos-muino-garcia you are absolutely right!

It was fixed as per your suggestion: https://github.com/timeoff-management/application/commit/5cfa0643d2524a717554cd78dc2f04dba6b4736e

Thank you for reporting.

**Comment by jekuno** [comment]
On the hosted timeoff version I created several users yesterday (at 2019-01-02), set the "started on" date (date the employee started) to 2019-01-01 and today discovered that days from 2018 had been carried over (which should not have happened as the employees did not exist in 2018). Is this the same issue?

**Comment by vpp** [comment]
Interesting.

I will investigate, thank you for reporting.

Thanks
Pavlo

**Comment by vpp** [comment]
@jekuno the issue should be fixed with https://github.com/timeoff-management/application/commit/b44026d97ca4d8079ae319c18ce8752c6d3bbcdf

Please make sure you rerun the carryover job.

**Comment by jekuno** [comment]
Thanks. After discovering this issue I already fixed the holidays using the individual adjustments for each employee on the hosted version. Now that I saw that you reran the script there I reverted the adjustments. Now everything seems fine.
