### ISSUE TITLE
Email subject misleading (leave request decided)

### ISSUE THREAD

**Issue by ralesk** [timeoff-management/application#333]
Every time I receive the email from timeoff saying that my leave request was decided I have to double-take because it really looks like "denied" on first sight.

That might be an error in me, but that subject line is also a bit of a clickbait/mystery meat operation — the information that it was approved is in the body, the subject could easily contain this already.

tl;dr: I think it would be awesome if the mail subject read _Leave request was {accepted|denied}_, depending on the situation.

**Comment by vpp** [comment]
@ralesk: good point.

I will add it into to be fixed soon, as it is easy to do and sounds very convenient for customers.
