### ISSUE TITLE
bulk user import does not work

### ISSUE THREAD

**Issue by vitas** [timeoff-management/application#335]
I have tried to export and import the same file and get the error:
Failed to import users, reason: Following departments could not be found in X account: "undefined"

**Comment by vpp** [comment]
hi @vitas, please use the example CSV file as a basis for file with new users.

**Comment by vitas** [comment]
I have downloaded example from step 1 and uploaded the same file again for import, so it has few real users.
Also, that file has an error Lastname and name has to be swapped, it exports it wrong order

**Comment by vpp** [comment]
oh.. thank you for pointing the issue of confusion with last name and first name.

**Comment by vpp** [comment]
@vitas looks like @Ingomancer fixed it in #339
