### ISSUE TITLE
CSV Header and data do not agree on field order

### ISSUE THREAD

**Issue by Ingomancer** [timeoff-management/application#339]
The CSV header when exporting users is "email,lastname,name,department", but the data is in the order email, name, lastname, department. The header or the data should be re-ordered to match the other one

**Comment by Ingomancer** [comment]
https://github.com/timeoff-management/application/blob/348f5e445db12fea0c5af1340bee32476a4bd7c9/lib/route/users.js#L219
here is the line where the header is added in front of the data, in not the same order as the data a few lines above

**Comment by Ingomancer** [comment]
As far as I could tell the user_importer code expects it to be in the same order as the header, so I changed the order of the exporter data.

**Comment by vpp** [comment]
Thank you @Ingomancer :)
