### ISSUE TITLE
allowancebytime.hbs

### ISSUE THREAD

**Issue by sampelje** [timeoff-management/application#343]
Hi,

line 114 -    <td data-vpp-deducted-days="1">{{ statistics.deducted_days }}</td>

returns zero for us.  what do I  need to do to get the calculation to work?
Also the "used" on the Statistics Calendar page also shows zero.

[Alico_employee_allowances_between2019_01_and_2019_12 (4).xlsx](https://github.com/timeoff-management/application/files/3049418/Alico_employee_allowances_between2019_01_and_2019_12.4.xlsx)

[2019-04-05_16-02-13.pdf](https://github.com/timeoff-management/application/files/3049440/2019-04-05_16-02-13.pdf)

**Comment by vpp** [comment]
hi @sampelje is the leave that to be deducted is approved? 
Is the type of that leave has `Use allowance` set ON?

**Comment by sampelje** [comment]
Ok,  error was the allowance was not set to On for that leave type.

 

Thank you!
