### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rixx** [timeoff-management/application#350]
The last release is nearly a year and a half old at this point. The last release of timeoff does not run on current (or even not-quite-current) versions of node, due to a dependency to rather old sqlite3. A new release would be highly appreciated, especially with an upgrade to sqlite3>=4.0.1.

**Comment by NightyLive** [comment]
I agree that sqlite3 fail to compile when doing npm install.

Debian 9
Node v10.16.0
npm 6.9.0

I fixed it by using : 
npm install https://github.com/mapbox/node-sqlite3/tarball/master
npm install
npm start

**Comment by XFactorus** [comment]
Is there any chance that separate vacations per departments will be added also to the new release?

It's marked as ready since June 2018 in https://github.com/timeoff-management/application/issues/41 but it is still not there

We highly need that feature.

**Comment by saschafoerster** [comment]
@vpp I see, that you are developing on the master version, but a new release would make it easier to upgrade and find help, if something doesn't work out. Thanks for the great tool anyway!

**Comment by vpp** [comment]
Long awaited release: https://github.com/timeoff-management/application/releases/tag/1.0.0
