### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by BeckeBauer** [timeoff-management/application#362]
Is there a documentation page with config sample for connection to mariaDB (or is it not possible at all)?
Also, I get a lot of error messages when I try to install the program; maybe, the documentation page contains hints for troubleshooting!?

**Comment by vpp** [comment]
hi @BeckeBauer 

App uses sequelize as a proxy to DB and looks like MariaDB is supported, so the app should work.

To configure I would suggest checkout out what needs to be passed to get connection to mariaBD here https://sequelize.org/master/manual/getting-started.html

And update db.json config in the same manner with relevant to your case values: https://github.com/timeoff-management/application/blob/master/config/db.json

Whatever is under `development`/`staging`/`production` section in that config goes straight into Sequelize

Regarding errors, you might want to use older node versions `v6.14.4` - it should work on that version.

**Comment by BeckeBauer** [comment]
Thank you vpp, I managed to install it as docker image (with slightly different configuration in the Dockerfile). I can confirm that it works with MariaDB 10.xx. My configuration in db.json:

 ```
{"development/test/production": {
    "username": "Username created in MariaDB",
    "password": "Password created in MariaDB",
    "database": "Name of database created in MariaDB",
    "host": "IP address of MariaDB",
    "port": 3307,
    "dialect": "mysql"
  }
```
