### ISSUE TITLE
Tooltip to include absence type

### ISSUE THREAD

**Issue by nbogol** [timeoff-management/application#374]
Please include absence type to the tooltip message when user mouse-over the calendar cell.
Currently it says "Approved absence" for any type of absence. Would be nice to have something like "Approved absence - ABSENCE_TYPE" for color-blinded folks.

**Comment by enriquetoledano** [comment]
In issue #242 Pavlo said he was going to do this.

**Comment by nbogol** [comment]
Pavlo, do you have any plans to implement this?

**Comment by vpp** [comment]
Done.
