### ISSUE TITLE
Can't see the admin gear

### ISSUE THREAD

**Issue by enordstrand** [timeoff-management/application#416]
I just installed timeoff-management, goes to "Register new company" and fills out the form. 
After I'm logged in with the user sepcified in the form, I see a drop down called "Me" at the top right. But i can't see the admin gear dropdown next to it, as I see in pictures on internet. In other words - I'm not able to create new employees. Is this a bug, or do you have any suggestions? The value for "Admin" on the user is set to 1. Shouldn't this be automatic enabled on the first user?

**Comment by danl2020** [comment]
I am having the same issue.  Weird thing is I have this installed on two identical Windows 10 VM's... one of them is working fine, the other is having this issue.  It looks like it wasn't installed fully.  Both running node v10.16, python 2.7.

**Comment by vpp** [comment]
Very weird... All automated tests are based on creation company for every scenario and manage it from perspective of admin user and they still work.
Does it happen on pristine checkout from `master`? Did you amend the config?
What environments you are running the app on?

As in @danl2020 comment - node v10.16 is correct.

**Comment by enordstrand** [comment]
Hello

Thank you for the reply! 
My environment is Windows 10 Enterprise, 64-bit, 8GB Ram. Running directly on the host (No VM for me). Tested with both Chrome and Firefox. Running commands from Powershell as Administrator.
npm -v: 6.13.4
node -v: 12.14.1
python version: 3.8.0

I did not change any config files. 
I'm not sure how to checkout pristine from master. Please let me know what more I can do to provide you further troubleshooting information. 

This is what I do to reproduce the issue:
mkdir test
cd test
git clone https://github.com/timeoff-management/application.git timeoff-management

cd timeoff-management

npm install

npm start

**Comment by vpp** [comment]
Hm...

All looks good.

Not sure what might be wrong...

Let’s see what other people say, as I do not have opportunity to run the app on Windows machine.

Thanks
Pavlo

**Comment by blewie** [comment]
Hello,

I am also missing the Admin gear. Fresh install on Centos.

**Comment by enordstrand** [comment]
Tried again 

Different computer, different network, different version of npm, node and python. Same result:
Windows 10 Pro
Node -v: 8.9.0
npm -v: 6.10.3
python --version: 2.7.13

Surprising, but interesting to see that I'm not the only one with this issue.

**Comment by blewie** [comment]
Tired different browsers. Firefox local on the VM, Chrome and IE on the remote computer. 

No change. Definitely not alone.

**Comment by vitorrsilva** [comment]
Hi 

I had the same problem..

was able to fix with 

npm i -D handlebars@4.5.0

**Comment by enordstrand** [comment]
Thanks, vitorrsilva! That worked! 
Not sure if I should close this before the admin gear is comming by default?

**Comment by blewie** [comment]
Thanks vitorrsilva. Confirmed this resolved my issue as well.

**Comment by bprfh** [comment]
Fixed for me as well.
Fedora 31
NPM 6.10.3

**Comment by tseabra** [comment]
@vitorrsilva FTW !! 
Thanks man

**Comment by Monkey777** [comment]
I have the same problem.. When I run the npm i -D handlebars@4.5.0 I just get the below message

__________________________
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\username\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\username\package.json'
npm WARN eslint-plugin-compat@3.3.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN username No description
npm WARN username No repository field.
npm WARN username No README data
npm WARN username No license field.

+ handlebars@4.5.0
added 21 packages from 55 contributors and audited 23 packages in 8.312s

1 package is looking for funding
  run `npm fund` for details

found 3 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details


______________

Tried on both in CentOS and Windows 2019

**Comment by bprfh** [comment]
@Monkey777 are you sure you are in the right directory ? to me it looks like your are not in the right directory.
You have to run the command in the same directory as the other files are.

**Comment by vitorrsilva** [comment]
@Monkey777 You are right

@bprfh you need to run command inside root project directory.

**Comment by Monkey777** [comment]
Oh sorry... Tried it again, both on server 2019 and CentOS but still don't have any admin gear to choose from... 

[username@hostname ~]$ cd timeoff-management/
[username@hostname timeoff-management]$ npm i -D handlebars@4.5.0 
npm WARN eslint-plugin-compat@3.3.0 requires a peer of eslint@^3.0.0 ||
^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN TimeOff.Management@1.0.0 No repository field.
npm WARN TimeOff.Management@1.0.0 No license field.

+ handlebars@4.5.0
added 13 packages from 13 contributors, updated 1 package and audited
2983 packages in 8.366s

15 packages are looking for funding
   run `npm fund` for details

found 21 vulnerabilities (4 low, 17 high)
   run `npm audit fix` to fix them, or `npm audit` for details
[username@hostname timeoff-management]$

**Comment by vpp** [comment]
Thank you guys for the all info.

I think the issue is due to handlebar became stricter https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access

**Comment by vpp** [comment]
Handlebars brought breaking changes as per link above.

To fix it properly we need to re-factore templates so the do not call any methods (which unfortunately they do at this moment). That would take awhile to do.

As a short term solution we need to add 
```
+    "handlebars": "4.5.0",
```
Into main dependencies.

**Comment by Monkey777** [comment]
> Handlebars brought breaking changes as per link above.
> To fix it properly we need to re-factore templates so the do not call any methods (which unfortunately they do at this moment). That would take awhile to do.
> As a short term solution we need to add
> +    "handlebars": "4.5.0",
> 
> Into main dependencies.

Super, how to I add it into main dependencies?

**Comment by vpp** [comment]
PR to fix: https://github.com/timeoff-management/application/pull/422

**Comment by vpp** [comment]
Merged to `master`.

guys, can you please confirm if it fixes the issue?

**Comment by enordstrand** [comment]
Confirm Admin gear is appearing with the new update.

Steps to verify:
cd g:
mkdir test
cd test
git clone https://github.com/timeoff-management/application.git timeoff-management
cd timeoff-management
npm install
npm start

created a company and user
when logged in, the gear appears. This time without writing: npm i -D handlebars@4.5.0

**Comment by vpp** [comment]
I think the proper solution to be implemented as part of general upgrading of dependencies.

So lets close this ticket.
