### ISSUE TITLE
Update Error - npm start - SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by ClaudioSousa14** [timeoff-management/application#417]
Hi,

I was having several issues trying to "carry-over-allowance" to move the remaining days of 2019 to 2020 so I decided to upgrade my software.

I can do every steps but I get an error when I do "npm start".

I have CentOS and I'm using sqlite DB.

Can you please help me?

Really Thank you.

I did this steps:

**I stopped the app**
[csousa@rh-dev timeoff-management]$ sudo pm2 stop rh
[PM2] Applying action stopProcessId on app [rh](ids: 0)
[PM2] [rh](0) ✓
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ rh       │ 0  │ fork │ 0   │ stopped │ 0       │ 0      │ 0%  │ 0 B    │ root │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

**git fetch**
[csousa@rh-dev timeoff-management]$ sudo git fetch
remote: Enumerating objects: 443, done.
remote: Counting objects: 100% (443/443), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 872 (delta 418), reused 434 (delta 415), pack-reused 429
Receiving objects: 100% (872/872), 277.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (617/617), completed with 125 local objects.
From https://github.com/timeoff-management/application
   f8dded8..65ecdb0  master     -> origin/master
 * [new branch]      audit      -> origin/audit
 * [new branch]      check-chrome-driver-base-tests -> origin/check-chrome-driver-base-tests
 * [new branch]      comments   -> origin/comments
 * [new branch]      node-verion-upgrade -> origin/node-verion-upgrade
 * [new branch]      node-version-upgrade -> origin/node-version-upgrade
 * [new branch]      test-with-phantom -> origin/test-with-phantom
 * [new branch]      tom-194-expose-user-calendar-to-admin -> origin/tom-194-expose-user-calendar-to-admin
 * [new branch]      tom-410-carry-over-and-accrual-alloance-issue -> origin/tom-410-carry-over-and-accrual-alloance-issue

**git pull origin master - error because I was trying to resolve the issues of carry-over. And my emails are different**
[csousa@rh-dev timeoff-management]$ sudo git pull origin master
From https://github.com/timeoff-management/application
 * branch            master     -> FETCH_HEAD
Updating f8dded8..65ecdb0
error: Your local changes to the following files would be overwritten by merge:
        bin/calculate_carry_over_allowance_for_all_users.js
        views/email/add_new_user.hbs
        views/email/confirm_registration.hbs
        views/email/forgot_password.hbs
        views/email/leave_request_cancel_to_requestor.hbs
        views/email/leave_request_cancel_to_supervisor.hbs
        views/email/leave_request_decision_to_requestor.hbs
        views/email/leave_request_decision_to_supervisor.hbs
        views/email/leave_request_revoke_to_requestor.hbs
        views/email/leave_request_revoke_to_requestor_autoapprove.hbs
        views/email/leave_request_revoke_to_supervisor.hbs
        views/email/leave_request_revoke_to_supervisor_autoapprove.hbs
        views/email/leave_request_to_requestor.hbs
        views/email/leave_request_to_requestor_autoapprove.hbs
        views/email/leave_request_to_supervisor.hbs
        views/email/leave_request_to_supervisor_autoapprove.hbs
        views/email/registration_complete.hbs
Please, commit your changes or stash them before you can merge.
Aborting

**git stash - to resolve the previous issue**
[csousa@rh-dev timeoff-management]$ sudo git stash
Saved working directory and index state WIP on master: f8dded8 Update tests to be compatible with new year
HEAD is now at f8dded8 Update tests to be compatible with new year

**git pull origin master**
[csousa@rh-dev timeoff-management]$ sudo git pull origin master
From https://github.com/timeoff-management/application
 * branch            master     -> FETCH_HEAD
Updating f8dded8..65ecdb0
Fast-forward
 .travis.yml                                                           |     8 +-
 Dockerfile                                                            |    35 +-
 README.md                                                             |    15 +-
 app.js                                                                |    14 +-
 bin/calculate_carry_over_allowance_for_all_users.js                   |    39 +-
 config/localisation.json                                              | 27788 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------
 lib/email.js                                                          |   264 +-
 lib/middleware/session_aware_redirect.js                              |     4 +-
 lib/model/audit.js                                                    |    38 +
 lib/model/calculateCarryOverAllowance.js                              |    46 +
 lib/model/calendar_month.js                                           |    18 +
 lib/model/comment.js                                                  |    31 +
 lib/model/db/audit.js                                                 |    57 +
 lib/model/db/comment.js                                               |    46 +
 lib/model/db/company.js                                               |    72 +-
 lib/model/db/email_audit.js                                           |     6 +-
 lib/model/db/leave.js                                                 |    19 +
 lib/model/db/user.js                                                  |    58 +-
 lib/model/leave/index.js                                              |     9 +
 lib/model/mixin/user/absence_aware.js                                 |     2 +-
 lib/model/mixin/user/company_aware.js                                 |     4 +-
 lib/model/user_allowance.js                                           |    22 +-
 lib/route/audit.js                                                    |    12 +-
 lib/route/bankHolidays.js                                             |   251 ++
 lib/route/calendar.js                                                 |    58 +-
 lib/route/dashboard.js                                                |     2 +-
 lib/route/departments.js                                              |    43 +-
 lib/route/feed.js                                                     |     6 +-
 lib/route/integration_api.js                                          |    43 +-
 lib/route/login.js                                                    |    29 +-
 lib/route/reports.js                                                  |    18 +-
 lib/route/requests.js                                                 |    13 +-
 lib/route/settings.js                                                 |   405 +--
 lib/route/{users.js => users/index.js}                                |   200 +-
 lib/route/users/summary.js                                            |    84 +
 lib/route/validator/leave_request.js                                  |    15 +-
 migrations/20190118-chnage-type-value-for-api-token.js                |    32 +
 migrations/20190629-add-is_team_view_hidden_field.js                  |    25 +
 migrations/20191030-compress-email-audit.js                           |    18 +
 package.json                                                          |    11 +-
 public/js/bank_holidays.js                                            |    25 +
 public/js/global.js                                                   |    22 +
 public/js/settings_general.js                                         |    26 -
 t/integration/bank_holidays/crud_bank_holiday.js                      |   115 +-
 t/integration/bank_holidays/non_default_date_format.js                |    42 +-
 t/integration/carryOver/justAddedUsers.js                             |   122 +
 t/integration/carryOver/negativeWhenSwitchedOff.js                    |   179 +
 t/integration/company/delete_account.js                               |     6 +-
 t/integration/crud_users.js                                           |     6 +
 t/integration/deactivate_and_activate_user.js                         |    22 +
 t/integration/employee_details_section/admin_view_of_user_calendar.js |   103 +
 t/integration/inactivate_user.js                                      |    13 +
 t/integration/integration_api/audit.js                                |   153 +
 t/integration/integration_api/enable_disable.js                       |   206 ++
 t/integration/leave_request/basic_leave_request.js                    |     5 +-
 t/integration/leave_request/cancel_basic.js                           |    10 +-
 t/integration/leave_request/create_leave_with_single_user.js          |     2 +-
 t/integration/leave_request/leave_request_revoke.js                   |    16 +-
 t/integration/leave_request/leave_request_revoke_by_admin.js          |    10 +-
 t/integration/leave_request/rendering_of_halves.js                    |    99 +-
 t/integration/leave_type/remove_used_leave_type.js                    |     2 +-
 t/integration/schedule/company_wide.js                                |     3 +-
 t/integration/schedule/user_specific.js                               |    22 +-
 t/integration/team_view/deducted_column.js                            |     8 +-
 t/integration/timezone.js                                             |    54 +-
 t/integration/try_to_open_private_pages_with_guest.js                 |    15 +-
 t/integration/try_to_revoke_admin_rights_from_last_admin.js           |     2 +-
 t/integration/users_import.js                                         |     2 +-
 t/lib/add_new_user.js                                                 |    14 +-
 t/lib/build_driver.js                                                 |    22 +
 t/lib/config.js                                                       |     2 +-
 t/lib/login_with_user.js                                              |    11 +-
 t/lib/mock_express_request.js                                         |     4 +-
 t/lib/register_new_user.js                                            |    18 +-
 t/lib/submit_form.js                                                  |    16 +
 t/unit/model/user_allowance.js                                        |    52 +
 views/audit/emails.hbs                                                |     2 +-
 views/bankHolidays.hbs                                                |   147 +
 views/calendar.hbs                                                    |     6 +-
 views/departments_overview.hbs                                        |     4 +-
 views/email/add_new_user.hbs                                          |     2 +-
 views/email/confirm_registration.hbs                                  |     2 +-
 views/email/forgot_password.hbs                                       |     7 +-
 views/email/leave_request_cancel_to_requestor.hbs                     |     2 +
 views/email/leave_request_cancel_to_supervisor.hbs                    |     2 +
 views/email/leave_request_decision_to_requestor.hbs                   |     4 +-
 views/email/leave_request_decision_to_supervisor.hbs                  |     2 +
 views/email/leave_request_revoke_to_requestor.hbs                     |     2 +
 views/email/leave_request_revoke_to_requestor_autoapprove.hbs         |     2 +
 views/email/leave_request_revoke_to_supervisor.hbs                    |     4 +-
 views/email/leave_request_revoke_to_supervisor_autoapprove.hbs        |     2 +
 views/email/leave_request_to_requestor.hbs                            |     4 +-
 views/email/leave_request_to_requestor_autoapprove.hbs                |     2 +
 views/email/leave_request_to_supervisor.hbs                           |     4 +
 views/email/leave_request_to_supervisor_autoapprove.hbs               |     2 +
 views/email/registration_complete.hbs                                 |     2 +-
 views/feeds_list.hbs                                                  |    11 +-
 views/general_settings.hbs                                            |   133 +-
 views/index.hbs                                                       |     2 +-
 views/partials/add_new_bank_holiday_modal.hbs                         |    15 +-
 views/partials/book_leave_modal.hbs                                   |     5 +
 views/partials/calendar_cell.hbs                                      |    13 +-
 views/partials/email/leave_comments.hbs                               |     7 +
 views/partials/email/requester_allowance.hbs                          |     6 +
 views/partials/footer.hbs                                             |     2 +-
 views/partials/header.hbs                                             |     5 +-
 views/partials/remove_company_modal.hbs                               |     2 +-
 views/partials/user_details/allowance_breakdown.hbs                   |     4 +-
 views/partials/user_details/calendar.hbs                              |    95 +
 views/report/allowancebytime.hbs                                      |     4 +-
 views/requests.hbs                                                    |     6 +-
 views/settings_company_authentication.hbs                             |    10 +-
 views/settings_company_integration_api.hbs                            |     8 +-
 views/team_view.hbs                                                   |     8 +-
 views/user/popup_user_details.hbs                                     |    20 +
 views/user_add.hbs                                                    |     2 +-
 views/user_details.hbs                                                |     9 +-
 views/users.hbs                                                       |     2 +-
 views/users_import.hbs                                                |     4 +-
 119 files changed, 26846 insertions(+), 5020 deletions(-)
 create mode 100644 lib/model/audit.js
 create mode 100644 lib/model/calculateCarryOverAllowance.js
 create mode 100644 lib/model/comment.js
 create mode 100644 lib/model/db/audit.js
 create mode 100644 lib/model/db/comment.js
 create mode 100644 lib/route/bankHolidays.js
 rename lib/route/{users.js => users/index.js} (84%)
 create mode 100644 lib/route/users/summary.js
 create mode 100644 migrations/20190118-chnage-type-value-for-api-token.js
 create mode 100644 migrations/20190629-add-is_team_view_hidden_field.js
 create mode 100644 migrations/20191030-compress-email-audit.js
 create mode 100644 public/js/bank_holidays.js
 create mode 100644 t/integration/carryOver/justAddedUsers.js
 create mode 100644 t/integration/carryOver/negativeWhenSwitchedOff.js
 create mode 100644 t/integration/employee_details_section/admin_view_of_user_calendar.js
 create mode 100644 t/integration/integration_api/audit.js
 create mode 100644 t/integration/integration_api/enable_disable.js
 create mode 100644 t/lib/build_driver.js
 create mode 100644 views/bankHolidays.hbs
 create mode 100644 views/partials/email/leave_comments.hbs
 create mode 100644 views/partials/email/requester_allowance.hbs
 create mode 100644 views/partials/user_details/calendar.hbs
 create mode 100644 views/user/popup_user_details.hbs

**npm install**
[csousa@rh-dev timeoff-management]$ sudo npm install

> sqlite3@4.1.1 install /var/www/timeoff-management/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "/var/www/timeoff-management/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node" is installed via remote
- graceful-readlink@1.0.1 node_modules/graceful-readlink
- lodash._baseassign@3.2.0 node_modules/lodash._baseassign
- lodash._basecreate@3.0.3 node_modules/lodash._basecreate
nopt@4.0.1 node_modules/sqlite3/node_modules/nopt -> node_modules/node-pre-gyp/node_modules/nopt
minimist@1.2.0 node_modules/sqlite3/node_modules/rc/node_modules/minimist -> node_modules/rc/node_modules/minimist
- abbrev@1.1.1 node_modules/sqlite3/node_modules/abbrev
- ansi-regex@2.1.1 node_modules/sqlite3/node_modules/ansi-regex
- aproba@1.2.0 node_modules/sqlite3/node_modules/aproba
- asn1@0.2.3 node_modules/sqlite3/node_modules/asn1
- assert-plus@0.2.0 node_modules/sqlite3/node_modules/assert-plus
- asynckit@0.4.0 node_modules/sqlite3/node_modules/asynckit
- aws-sign2@0.6.0 node_modules/sqlite3/node_modules/aws-sign2
- aws4@1.6.0 node_modules/sqlite3/node_modules/aws4
- balanced-match@1.0.0 node_modules/sqlite3/node_modules/balanced-match
- caseless@0.12.0 node_modules/sqlite3/node_modules/caseless
- co@4.6.0 node_modules/sqlite3/node_modules/co
- code-point-at@1.1.0 node_modules/sqlite3/node_modules/code-point-at
- concat-map@0.0.1 node_modules/sqlite3/node_modules/concat-map
- brace-expansion@1.1.8 node_modules/sqlite3/node_modules/brace-expansion
- console-control-strings@1.1.0 node_modules/sqlite3/node_modules/console-control-strings
- core-util-is@1.0.2 node_modules/sqlite3/node_modules/core-util-is
- assert-plus@1.0.0 node_modules/sqlite3/node_modules/dashdash/node_modules/assert-plus
- dashdash@1.14.1 node_modules/sqlite3/node_modules/dashdash
- deep-extend@0.4.2 node_modules/sqlite3/node_modules/deep-extend
- delayed-stream@1.0.0 node_modules/sqlite3/node_modules/delayed-stream
- combined-stream@1.0.5 node_modules/sqlite3/node_modules/combined-stream
- delegates@1.0.0 node_modules/sqlite3/node_modules/delegates
- extend@3.0.1 node_modules/sqlite3/node_modules/extend
- extsprintf@1.3.0 node_modules/sqlite3/node_modules/extsprintf
- forever-agent@0.6.1 node_modules/sqlite3/node_modules/forever-agent
- fs.realpath@1.0.0 node_modules/sqlite3/node_modules/fs.realpath
- assert-plus@1.0.0 node_modules/sqlite3/node_modules/getpass/node_modules/assert-plus
- getpass@0.1.7 node_modules/sqlite3/node_modules/getpass
- graceful-fs@4.1.11 node_modules/sqlite3/node_modules/graceful-fs
- har-schema@1.0.5 node_modules/sqlite3/node_modules/har-schema
- has-unicode@2.0.1 node_modules/sqlite3/node_modules/has-unicode
- hoek@2.16.3 node_modules/sqlite3/node_modules/hoek
- boom@2.10.1 node_modules/sqlite3/node_modules/boom
- cryptiles@2.0.5 node_modules/sqlite3/node_modules/cryptiles
- inherits@2.0.3 node_modules/sqlite3/node_modules/inherits
- block-stream@0.0.9 node_modules/sqlite3/node_modules/block-stream
- ini@1.3.4 node_modules/sqlite3/node_modules/ini
- is-typedarray@1.0.0 node_modules/sqlite3/node_modules/is-typedarray
- isarray@1.0.0 node_modules/sqlite3/node_modules/isarray
- isstream@0.1.2 node_modules/sqlite3/node_modules/isstream
- jsbn@0.1.1 node_modules/sqlite3/node_modules/jsbn
- ecc-jsbn@0.1.1 node_modules/sqlite3/node_modules/ecc-jsbn
- json-schema@0.2.3 node_modules/sqlite3/node_modules/json-schema
- json-stringify-safe@5.0.1 node_modules/sqlite3/node_modules/json-stringify-safe
- jsonify@0.0.0 node_modules/sqlite3/node_modules/jsonify
- json-stable-stringify@1.0.1 node_modules/sqlite3/node_modules/json-stable-stringify
- ajv@4.11.8 node_modules/sqlite3/node_modules/ajv
- har-validator@4.2.1 node_modules/sqlite3/node_modules/har-validator
- assert-plus@1.0.0 node_modules/sqlite3/node_modules/jsprim/node_modules/assert-plus
- mime-db@1.30.0 node_modules/sqlite3/node_modules/mime-db
- mime-types@2.1.17 node_modules/sqlite3/node_modules/mime-types
- form-data@2.1.4 node_modules/sqlite3/node_modules/form-data
- minimatch@3.0.4 node_modules/sqlite3/node_modules/minimatch
- minimist@0.0.8 node_modules/sqlite3/node_modules/minimist
- mkdirp@0.5.1 node_modules/sqlite3/node_modules/mkdirp
- ms@2.0.0 node_modules/sqlite3/node_modules/ms
- debug@2.6.9 node_modules/sqlite3/node_modules/debug
- number-is-nan@1.0.1 node_modules/sqlite3/node_modules/number-is-nan
- is-fullwidth-code-point@1.0.0 node_modules/sqlite3/node_modules/is-fullwidth-code-point
- oauth-sign@0.8.2 node_modules/sqlite3/node_modules/oauth-sign
- object-assign@4.1.1 node_modules/sqlite3/node_modules/object-assign
- os-homedir@1.0.2 node_modules/sqlite3/node_modules/os-homedir
- os-tmpdir@1.0.2 node_modules/sqlite3/node_modules/os-tmpdir
- osenv@0.1.4 node_modules/sqlite3/node_modules/osenv
- path-is-absolute@1.0.1 node_modules/sqlite3/node_modules/path-is-absolute
- performance-now@0.2.0 node_modules/sqlite3/node_modules/performance-now
- process-nextick-args@1.0.7 node_modules/sqlite3/node_modules/process-nextick-args
- punycode@1.4.1 node_modules/sqlite3/node_modules/punycode
- qs@6.4.0 node_modules/sqlite3/node_modules/qs
- rc@1.2.1 node_modules/sqlite3/node_modules/rc
- safe-buffer@5.1.1 node_modules/sqlite3/node_modules/safe-buffer
- semver@5.4.1 node_modules/sqlite3/node_modules/semver
- set-blocking@2.0.0 node_modules/sqlite3/node_modules/set-blocking
- signal-exit@3.0.2 node_modules/sqlite3/node_modules/signal-exit
- sntp@1.0.9 node_modules/sqlite3/node_modules/sntp
- hawk@3.1.3 node_modules/sqlite3/node_modules/hawk
- assert-plus@1.0.0 node_modules/sqlite3/node_modules/sshpk/node_modules/assert-plus
- string_decoder@1.0.3 node_modules/sqlite3/node_modules/string_decoder
- stringstream@0.0.5 node_modules/sqlite3/node_modules/stringstream
- strip-ansi@3.0.1 node_modules/sqlite3/node_modules/strip-ansi
- string-width@1.0.2 node_modules/sqlite3/node_modules/string-width
- tough-cookie@2.3.3 node_modules/sqlite3/node_modules/tough-cookie
- tunnel-agent@0.6.0 node_modules/sqlite3/node_modules/tunnel-agent
- tweetnacl@0.14.5 node_modules/sqlite3/node_modules/tweetnacl
- bcrypt-pbkdf@1.0.1 node_modules/sqlite3/node_modules/bcrypt-pbkdf
- sshpk@1.13.1 node_modules/sqlite3/node_modules/sshpk
- uid-number@0.0.6 node_modules/sqlite3/node_modules/uid-number
- util-deprecate@1.0.2 node_modules/sqlite3/node_modules/util-deprecate
- readable-stream@2.3.3 node_modules/sqlite3/node_modules/readable-stream
- are-we-there-yet@1.1.4 node_modules/sqlite3/node_modules/are-we-there-yet
- uuid@3.1.0 node_modules/sqlite3/node_modules/uuid
- assert-plus@1.0.0 node_modules/sqlite3/node_modules/verror/node_modules/assert-plus
- verror@1.10.0 node_modules/sqlite3/node_modules/verror
- jsprim@1.4.1 node_modules/sqlite3/node_modules/jsprim
- http-signature@1.1.1 node_modules/sqlite3/node_modules/http-signature
- request@2.81.0 node_modules/sqlite3/node_modules/request
- wide-align@1.1.2 node_modules/sqlite3/node_modules/wide-align
- gauge@2.7.4 node_modules/sqlite3/node_modules/gauge
- npmlog@4.1.2 node_modules/sqlite3/node_modules/npmlog
- wrappy@1.0.2 node_modules/sqlite3/node_modules/wrappy
- once@1.4.0 node_modules/sqlite3/node_modules/once
- inflight@1.0.6 node_modules/sqlite3/node_modules/inflight
- glob@7.1.2 node_modules/sqlite3/node_modules/glob
- rimraf@2.6.2 node_modules/sqlite3/node_modules/rimraf
- fstream@1.0.11 node_modules/sqlite3/node_modules/fstream
- fstream-ignore@1.0.5 node_modules/sqlite3/node_modules/fstream-ignore
- tar@2.2.1 node_modules/sqlite3/node_modules/tar
- tar-pack@3.4.0 node_modules/sqlite3/node_modules/tar-pack
strip-json-comments@2.0.1 node_modules/sqlite3/node_modules/strip-json-comments -> node_modules/strip-json-comments
- json3@3.3.2 node_modules/json3
- lodash.create@3.1.1 node_modules/lodash.create
- commander@2.9.0 node_modules/mocha/node_modules/commander
- nan@2.7.0 node_modules/sqlite3/node_modules/nan
- node-pre-gyp@0.6.38 node_modules/sqlite3/node_modules/node-pre-gyp
TimeOff.Management@1.0.0 /var/www/timeoff-management
├─┬ mocha@6.2.2
│ ├── ansi-colors@3.2.3
│ ├── browser-stdout@1.3.1
│ ├── debug@3.2.6
│ ├── diff@3.5.0
│ ├─┬ find-up@3.0.0
│ │ └─┬ locate-path@3.0.0
│ │   ├─┬ p-locate@3.0.0
│ │   │ └─┬ p-limit@2.2.2
│ │   │   └── p-try@2.2.0
│ │   └── path-exists@3.0.0
│ ├── glob@7.1.3
│ ├── growl@1.10.5
│ ├── he@1.2.0
│ ├─┬ js-yaml@3.13.1
│ │ ├─┬ argparse@1.0.10
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@4.0.1
│ ├─┬ log-symbols@2.2.0
│ │ └─┬ chalk@2.4.2
│ │   ├─┬ ansi-styles@3.2.1
│ │   │ └─┬ color-convert@1.9.3
│ │   │   └── color-name@1.1.3
│ │   └── supports-color@5.5.0
│ ├── ms@2.1.1
│ ├─┬ node-environment-flags@1.0.5
│ │ ├─┬ object.getownpropertydescriptors@2.1.0
│ │ │ └─┬ es-abstract@1.17.0
│ │ │   ├─┬ es-to-primitive@1.2.1
│ │ │   │ ├── is-date-object@1.0.2
│ │ │   │ └─┬ is-symbol@1.0.3
│ │ │   │   └── has-symbols@1.0.1
│ │ │   ├── has@1.0.3
│ │ │   ├── has-symbols@1.0.1
│ │ │   ├── is-callable@1.1.5
│ │ │   ├── is-regex@1.0.5
│ │ │   ├── object-inspect@1.7.0
│ │ │   ├── object-keys@1.1.1
│ │ │   ├── string.prototype.trimleft@2.1.1
│ │ │   └── string.prototype.trimright@2.1.1
│ │ └── semver@5.7.1
│ ├─┬ supports-color@6.0.0
│ │ └── has-flag@3.0.0
│ ├─┬ yargs@13.3.0
│ │ ├─┬ cliui@5.0.0
│ │ │ ├─┬ strip-ansi@5.2.0
│ │ │ │ └── ansi-regex@4.1.0
│ │ │ └─┬ wrap-ansi@5.1.0
│ │ │   └── ansi-styles@3.2.1
│ │ ├── get-caller-file@2.0.5
│ │ ├── require-main-filename@2.0.0
│ │ ├─┬ string-width@3.1.0
│ │ │ ├── emoji-regex@7.0.3
│ │ │ └── is-fullwidth-code-point@2.0.0
│ │ ├── which-module@2.0.0
│ │ └── y18n@4.0.0
│ ├─┬ yargs-parser@13.1.1
│ │ └── camelcase@5.3.1
│ └─┬ yargs-unparser@1.6.0
│   ├─┬ flat@4.1.0
│   │ └── is-buffer@2.0.4
│   ├── lodash@4.17.15
│   └─┬ yargs@13.3.0
│     ├─┬ cliui@5.0.0
│     │ ├─┬ strip-ansi@5.2.0
│     │ │ └── ansi-regex@4.1.0
│     │ └─┬ wrap-ansi@5.1.0
│     │   └── ansi-styles@3.2.1
│     ├── find-up@3.0.0
│     ├── get-caller-file@2.0.5
│     ├── require-main-filename@2.0.0
│     ├─┬ string-width@3.1.0
│     │ └── is-fullwidth-code-point@2.0.0
│     ├── which-module@2.0.0
│     ├── y18n@4.0.0
│     └─┬ yargs-parser@13.1.1
│       └── camelcase@5.3.1
├─┬ request-promise@4.2.5
│ ├── bluebird@3.7.2
│ ├─┬ request-promise-core@1.1.3
│ │ └── lodash@4.17.15
│ └── stealthy-require@1.1.1
└─┬ sqlite3@4.1.1
  └─┬ node-pre-gyp@0.11.0
    ├── detect-libc@1.0.3
    ├─┬ needle@2.4.0
    │ ├─┬ debug@3.2.6
    │ │ └── ms@2.1.2
    │ └── sax@1.2.4
    ├─┬ npm-packlist@1.4.7
    │ ├── ignore-walk@3.0.3
    │ └─┬ npm-bundled@1.1.1
    │   └── npm-normalize-package-bin@1.0.1
    ├─┬ rc@1.2.8
    │ └── deep-extend@0.6.0
    ├─┬ rimraf@2.7.1
    │ └── glob@7.1.6
    └─┬ tar@4.4.13
      ├── chownr@1.1.3
      ├── fs-minipass@1.2.7
      ├─┬ minipass@2.9.0
      │ └── safe-buffer@5.2.0
      ├── minizlib@1.3.3
      └── safe-buffer@5.2.0

npm WARN TimeOff.Management@1.0.0 No repository field.
npm WARN TimeOff.Management@1.0.0 No license field.

**npm run-script db-update**
[csousa@rh-dev timeoff-management]$ sudo npm run-script db-update

> TimeOff.Management@1.0.0 db-update /var/www/timeoff-management
> node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/

Sequelize [Node: 6.17.1, CLI: 2.5.1, ORM: 3.33.0, sqlite3: ^4.0.1]

Loaded configuration file "config/db.json".
Using environment "development".
== 20190118-chnage-type-value-for-api-token: migrating =======
== 20190118-chnage-type-value-for-api-token: migrated (0.672s)
== 20190629-add-is_team_view_hidden_field: migrating =======
== 20190629-add-is_team_view_hidden_field: migrated (0.034s)
== 20191030-compress-email-audit: migrating =======
Done!
== 20191030-compress-email-audit: migrated (72.707s)

**ERROR when do npm start**
[csousa@rh-dev timeoff-management]$ sudo npm start

> TimeOff.Management@1.0.0 start /var/www/timeoff-management
> node bin/wwww

/var/www/timeoff-management/lib/route/bankHolidays.js:79
  return model.BankHoliday.create({...attributes, companyId});
                                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/timeoff-management/app.js:132:23)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/timeoff-management/bin/wwww:4:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

npm ERR! Linux 3.10.0-957.27.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! TimeOff.Management@1.0.0 start: `node bin/wwww`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TimeOff.Management@1.0.0 start script 'node bin/wwww'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the TimeOff.Management package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/wwww
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs TimeOff.Management
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls TimeOff.Management
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/timeoff-management/npm-debug.log

**Comment by vpp** [comment]
The minimum version of node was recently bumped up to 10.16

Please update your environment to use that version of node.js

Thanks
Pavlo

**Comment by ClaudioSousa14** [comment]
Thank for the help and fast response.

So I upgraded the node.js from v6.17.1 to v10.16.3.

No problems doing "npm install" but when I did "npm run-script db-update" I got the following error:

[csousa@rh-dev timeoff-management]$ sudo npm run-script db-update

> TimeOff.Management@0.10.0 db-update /var/www/timeoff-management
> node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/


Sequelize [Node: 10.16.3, CLI: 2.5.1, ORM: 3.33.0, sqlite3: ^3.1.1]

internal/util/inspect.js:31
const types = internalBinding('types');
              ^

ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/var/www/timeoff-management/node_modules/natives/index.js:137:5)
    at require (/var/www/timeoff-management/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/var/www/timeoff-management/node_modules/natives/index.js:137:5)
    at require (/var/www/timeoff-management/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/var/www/timeoff-management/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/var/www/timeoff-management/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/var/www/timeoff-management/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)

npm ERR! Linux 3.10.0-957.27.2.el7.x86_64
npm ERR! argv "/usr/local/n/versions/node/10.16.3/bin/node" "/bin/npm" "run-script" "db-update"
npm ERR! node v10.16.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! TimeOff.Management@0.10.0 db-update: `node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TimeOff.Management@0.10.0 db-update script 'node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the TimeOff.Management package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs TimeOff.Management
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls TimeOff.Management
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/timeoff-management/npm-debug.log

**Comment by ClaudioSousa14** [comment]
Problem resolved.

So with node.js v6.17.1 I did:
```
# sudo git fetch
# sudo git pull origin master
# sudo npm install
# sudo npm run-script db-update
```

Then I updated node.js from v6.17.1 to v10.16.3 :
```
# sudo node -v
# sudo npm cache clean -f
# sudo npm install -g n
# sudo n 10.16
# sudo ln -sf /usr/local/n/versions/node/10.16.3/bin/node /usr/bin/node
# sudo node -v
```

Then I get and error of "Please install sqlite3 package manually", so I need to do:
`# sudo npm install sqlite3
`
After the end I could:
`# npm start`

Application working with no problems at all.
Thank you.
