### ISSUE TITLE
Accrued allowance feature

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#43]
Currently the application allocate the number of free time off days at the start of the year and employee is able to spend them at any point.

Few customers asked for feature when the allowance is accrued based on how far in the current year we are now.

"... We would need some notion of accrued time. Instead of having a fixed amount of time available at the beginning of the year, we officially accrue time based on an annual rate. If you had 12 vacation days per year, you would accrue 1 day per month (or more precisely, a certain amount per day). This is useful for 2 cases ..."

To implement this feature we do not need to do any DB changes other than adding new flag to the company level - that enables/disables it.

The business logic needs to be amended such a way that when requesting new leave system checks if user still within accrued number of available days.

That feature overlaps with some functionality discussed in #37

**Comment by vpp** [comment]
Got interest from one more person.

**Comment by vpp** [comment]
More interest from customers.

**Comment by opswhisperer** [comment]
+1 Accrual should be in days per period or % per period.  Periods corresponding to pay cycles, monthly weekly bi-weekly

**Comment by vpp** [comment]
One more person is asking for this.

**Comment by vpp** [comment]
Accrues are defined by:
* days to accrue on every period
* schedule (month, fortnight, months) and date

I think in case of TOM it will be days based rather then hours based and more likely on month base. Also the precision is going to be up to .5 day.

**Comment by vpp** [comment]
One more person asked for the feature:

> I would like to track accruals for PTO and Sick time.

**Comment by vpp** [comment]
Let David (email from 1 Aug) know when the feature is done.

**Comment by vpp** [comment]
One more person asked for the feature

**Comment by darntough** [comment]
I too am interested in this.  It would be SUPER!  Also if it could use hours instead of days.  If you guys need help, I'd be more than happy to poke around the code...

**Comment by vpp** [comment]
Thank you @darntough

**Comment by vpp** [comment]
One more person asked about this feature. So it needs to go into progress.

**Comment by nm2501** [comment]
+1 I'd love to see this feature too. The holiday policy at my company is N days per year, which are accrued month-by-month at 1/12th of the yearly allowance. 
This could make it tricky to show how much holiday you have accrued when the actual value is something like 21.666666666.

**Comment by ChoiceTL** [comment]
I would love to see that you could select the amount of hours your want to take as leave of absence as well. Our company gives employees 27,5 days off per year, but those can be used by the employees per hour.

**Comment by kenshi1023** [comment]
+1

**Comment by vpp** [comment]
The feature is in master.

Now it is possible to set given department to have its employe with accrual holiday entitlements.
