### ISSUE TITLE
UI: add_new_leave_type_btn overlap

### ISSUE THREAD

**Issue by kai3x5** [timeoff-management/application#47]
Not sure if intentional but the "Add new" button is overlapping the "Save changes" button.

## Before changing button padding:
<img width="288" alt="hud5und" src="https://cloud.githubusercontent.com/assets/11261243/13036467/c4df4b6e-d32d-11e5-9629-2b778e397669.png">

## After changing button padding:
<img width="306" alt="toqdmgp" src="https://cloud.githubusercontent.com/assets/11261243/13036471/c8034188-d32d-11e5-93c7-1e7119571c56.png">

**Comment by vpp** [comment]
Thanks @kai3x5, I will put the fix into the master.

**Comment by vpp** [comment]
Fixed.
