### ISSUE TITLE
Postgres does not like lowcased names

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#57]
Customer reported that in order to make TOM work with PostgreSQL one need to do this tweak;

--- a/lib/model/db/leave.js
+++ b/lib/model/db/leave.js
@@ -57,7 +57,7 @@ module.exports = function(sequelize, DataTypes) {
             fields : ['leaveTypeId'],
           },
           {
-            fields : ['approverid'],
-            fields : ['approverId'],
         },
       ],
       classMethods : {

**Comment by jekuno** [comment]
Fixed by #126
