### ISSUE TITLE
Transferring unused holidays to next year

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#6]
System should automatically transfer all remaining vacation days to the next year.

Alternatively when calculating employee allowance previous year should be taken into consideration.

Some notes on implementation:

* Linking table to user: carried_over_allowance. With fields: id, user_id, year, carried_over_allowance, suggested_allowance
* Supervisor automatically sees missing carry overs on the my requests page (the section to be renamed into My messages)
* Employee details page allows to amend carried over but not to exceed the suggested value. In case when user want to have more, suggest manual allowance adjustments
* Send email to employee when her allowance was carried over
* Department or Company has a property that could define max amount of carried over days

**Comment by vpp** [comment]
Consider naming feature "residual allowance"

**Comment by vpp** [comment]
Held till next year.

**Comment by theapprover** [comment]
I would like to express interest in this feature or a similar feature that allows us to manually enter Accrued Vacation Days / Holidays from prior periods for specific employees.

Another related request would be the ability to alter the vacation days per employee (+/- Days similar to how we can increase or decrease Allowance) e.g. We have a policy where Vacation is given at 3 weeks per year until you have been with the company for 5 years and then you are entitled to 4 weeks vacation.

**Comment by vpp** [comment]
Ended up implementing feature as: each employ per every year has a record with general adjustment and remaining allocation brought from previous year.

Calculation of carry over happens only as a result of running command:

npm run-script carry-over-allowance
