### ISSUE TITLE
UX improvements for creating new leave request

### ISSUE THREAD

**Issue by vpp** [timeoff-management/application#60]
As per customer request:

> 4) It would be really handy if after selecting start date  in
> calendar, calendar for end date would jump to same month

**Comment by vpp** [comment]
The point in description is going to be true only if START date is later then END one.

**Comment by jekuno** [comment]
I think the request means the following:
If it's April currently and I want to add a leave request for October I select e.g. 10th of October as a start date and the end date gets set to 10th of October automatically so that I don't have to set the end date to October manually.

**Comment by vpp** [comment]
Hi @jekuno,

This exactly how the feature was implemented recently.

**Comment by jekuno** [comment]
All right! I thought you meant to reject the issue. ;)
