### ISSUE TITLE
Little bug in add_new_department_modal.hbs

### ISSUE THREAD

**Issue by enriquetoledano** [timeoff-management/application#70]
Line 43 of add_new_department_modal.hbs should be 
`<option value="{{this.id}}">{{this.full_name}}</option>` 
instead of 
`<option value="{{this.id}}">{{this.name}}</option>`
Best regards

**Comment by vpp** [comment]
Good spot! Thanks! Will update master shortly.

**Comment by vpp** [comment]
Merged into master and deployed on timeoff.management
