### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by enriquetoledano** [timeoff-management/application#72]
Some typos:

settings.js 639
Failed to validate new LDAP settings with provided current user passwprd
Failed to validate new LDAP settings with provided current user password

users.js 534
req.session.flash_error('Provoded department is incorrect');
req.session.flash_error('Provided department is incorrect');

calendar_cell.hbs 24
{{#if this.is_pended_revoke_leave}}Revoked waiting for appoval{{/if}}
{{#if this.is_pended_revoke_leave}}Revoked waiting for approval{{/if}}

calendar_cell.hbs 26
{{#unless this.is_pended_revoke_leave}}Appoved absense{{/unless}}
{{#unless this.is_pended_revoke_leave}}Approved absence{{/unless}}

Best Regards

**Comment by vpp** [comment]
Thank you @enriquetoledano  for spotting those typos.
