### ISSUE TITLE
Bug in calendar view

### ISSUE THREAD

**Issue by enriquetoledano** [timeoff-management/application#73]
The name of the supervisor that approves the leave is not showing in the calendar view under "Approved by"

Best regards

**Comment by j-ledoux** [comment]
Hi, 
I tried to fix it on my fork, not sure if it's the proper way to do it, but it worked.
https://github.com/j-ledoux/application/commit/d22eb5afe642f81e126be8e670eba5b462998513

**Comment by vpp** [comment]
Hi @j-ledoux, yeah it is one of options but it makes the underlying query to produce cartesian product of users (at this moment it is priduct of types by users): users x approvers x types.  That is OK when there are small number of users but when it grwos the memory footprint grows as well.
I was thinking to add approvers in separate query after the one you've updated is done.
