### ISSUE TITLE
Bug when creating leaves for next year

### ISSUE THREAD

**Issue by enriquetoledano** [timeoff-management/application#76]
Hi:

When a new leave request is created for the next year, the number of days used for the type is not checked against the max of allowed days of the type.

For example, if I have defined a type named "X" that has a max number of days of 1.
Let's suppose that I ask 1 day of type X for next year and it's granted. When I ask again for 1 day of type X for next year, the system let me ask for it, and it can even be granted.

Best Regards!

**Comment by vpp** [comment]
Hi @enriquetoledano! Thank you for reporting this issue. I will have a look into it. It definitely a bug.

**Comment by vpp** [comment]
Fixed and deployed on TimeOff.Management.

@enriquetoledano, thank you again for reporting!
