### ISSUE TITLE
Annual Exception

### ISSUE THREAD

**Issue by PatrickFist** [timeoff-management/application#83]
Hi,

how to treat a annual exception? E.g. John.Doe changes 5 paid off days into cash money with his boss. This happens rarely but might happen. Would be great if the Option "Allowance adjustment per User" would reflect a adjustment by anno not general.
If I put him -5 today. He would have -5 again next year.

cheers :).

**Comment by vpp** [comment]
Hi @PatrickFist, good idea.

And needs to be consider this year. I will think about it.

**Comment by vpp** [comment]
Allowance adjustments now are on individual year basis, that is if employee X got adjustment of +3 days it is applied only to current year.

Done as part of #209
