### ISSUE TITLE
'Fork me on Github' banner covers 'Sign up' button

### ISSUE THREAD

**Issue by alexdrans** [timeoff-management/application#85]
![image](https://cloud.githubusercontent.com/assets/2844540/20640550/f7e84a06-b3d8-11e6-914a-c01ef062959c.png)

Screen sizes sm and md

**Comment by vpp** [comment]
hi @alexdrans! good spot, thank you!

**Comment by vpp** [comment]
Hide "fork me" badge in sm and md screens.
