### ISSUE TITLE
Amend Holiday Entitlement for individuals after User creation

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#86]
Hi There, 

I'm currently evaluating timeoff-management in order to see if it would be suitable for our company of around 80 staff.  So far, it's looking brilliantly so thank you for making it open source.

We increase our staff's holiday entitlement by 1 extra day per year they've been with the company, can individual users' entitlement be increased manually once their user account has been created?

I couldn't see anywhere to do this.  I did see adjustment options in the users settings but it won't let me save them without giving them a new email address and resetting their password.

Kind Regards,

**Comment by vpp** [comment]
Hi @AsimPervez93,

The "Allowance adjustment" field on employee details page is a way to adjust allowance on individual basis.  

When changing its value it is not necessary to enter new password. If password field is empty, system just ignore it.

So it is safe to save employee details without entering new values to email/password or any other attributes.

**Comment by vpp** [comment]
We need to add feature of auto adjustments based on employment period.

**Comment by AsimPervez93** [comment]
Thanks for your reply.  When I click on the user Joe Bloggs, the details for a different user are autofilled.  Then when I take away the password and email address (as I dont want them to change), it will not let me save the changes.

![image](https://cloud.githubusercontent.com/assets/17923501/20831621/bd1130e2-b87d-11e6-9a09-5fbe554db0d2.png)

**Comment by vpp** [comment]
@AsimPervez93, it sounds weird...

Maybe it is your browser automatically fills in email and password assuming that this is a login screen?

**Comment by vpp** [comment]
I think we need to update the names of email and password fields on that page to avoid browser's confusion.

**Comment by AsimPervez93** [comment]
You're absolutely correct.  It was my browser auto filling the details and causing confusion.

I've been able to successfully adjust the allowance.

Thank you for your assistance.  I'm going to happily continue evaluating the system for our company.

**Comment by vpp** [comment]
@AsimPervez93, cool!

Feel free to comment/suggest issues/ideas, your feedback is much appreciated.

**Comment by vpp** [comment]
@AsimPervez93, just fyi, I've updated app to use different names for email and password form parameters. So browser does not confuse the edit/add user form anymore.
