### ISSUE TITLE
Email Configuration & Testing

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#90]
I've been evaluating the system but have no email functionality.  

After looking in the files am I correct in saying that the email configuration is set in /config/app.json?

If so, how can I test if the configuration entered is working correctly?

**Comment by vpp** [comment]
hi @AsimPervez93,

Absolutely, the https://github.com/timeoff-management/application/blob/master/config/app.json is a config file to update. make sure that send_emails flag is set to be true alongside with correct credentials in email_transporter section.

Regarding confirmation of correct configuration: obvious way is to check that email is delivered, and check logs to miss any fatal errors.

**Comment by AsimPervez93** [comment]
Thanks for the reply.  I'll be testing email functionality with Exchange 2010 today and tomorrow.

**Comment by AsimPervez93** [comment]
Hi @vpp 

I'm still having trouble setting this up with any mail service. I've tried with our Exchange server and I've also tried with out Shared Hosting email service and none are working.

Could you have a look at the code and maybe spot if I'm doing something wrong?

> {
  "allow_create_new_accounts" : false,
  "send_emails"              : true,
  "application_sender_email" : "admin@1stintegrated.co.uk",
  "email_transporter" : {
    "host" : "elysium.krystal.co.uk",
    "port" : 465,
    "auth" : {
      "user" : "admin@1stintegrated.co.uk",
      "pass" : "parlay001"
    }
  },
  "crypto_secret" : "!2~`HswpPPLa22+=±§sdq qwe,appp qwwokDF_"
}

**Comment by vpp** [comment]
hi  @AsimPervez93 

The config chunk look OK.

Did you check the spam folder. Sometimes when sending host (elysium.krystal.co.uk) does not match host from sending email (1stintegrated.co.uk) such email messages are treated as spam.
