### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by sawan1990** [timeoff-management/application#91]
Here is one of the test but same error for all of the others

23) Register new user Check default registration path:
     Error: Waiting element to be located by By.cssSelector("h1")
Wait timed out after 1073ms

**Comment by vpp** [comment]
hi @sawan1990!

Interesting issue..

Looks very likely that application server was not started.

The main tests for the project are webdiver based high level integration tests that required  application with default settings to be up and running . 

I think I need to mention it in README section.

**Comment by vpp** [comment]
README was updated.
