### ISSUE TITLE
Secure with SSL

### ISSUE THREAD

**Issue by AsimPervez93** [timeoff-management/application#92]
Hi Pavlo, 

I've set my instance to run on Ubuntu, I've also set a subdomain to redirect to my instance of Timeoff, which works correctly.

At the moment all traffic is through http, I'd like to secure this using SSL, are you aware of any problems I might encounter doing this or do you have any advice?

Kind Regards,

**Comment by vpp** [comment]
hi @AsimPervez93!

I am not aware of any at this moment. Feel free to ping me if you have some problems.

**Comment by AsimPervez93** [comment]
Hi Pavlo, 

I'm having some trouble understanding how to get node.js secured with SSL.  I've done some Google'ing but it only really gives information if you are creating an application, rather than securing an existing one.

Can you provide some guidance?

Kind Regards,

**Comment by vpp** [comment]
hi @AsimPervez93, I did not have chance to setup the app behind ssl yet, so not aware of any surprises that could surface..

There was a plan to setup ssl for publicly available timeoff.management application, but it is still in pipeline..

**Comment by AsimPervez93** [comment]
Hi Pavlo, 

I trust you had a good Christmas and New Year?

The difficulty I'm facing at the moment is that in order to send emails, my hosting provider require that mail be sent through an SSL connection, therefore I can't test out email functionality until I have secured the application with SSL.

Could you possibly provide some guidance on how I could do this?

Kind Regards,
