### ISSUE TITLE
Improve teamview calendar half days rendering

### ISSUE THREAD

**Issue by j-ledoux** [timeoff-management/application#93]
Hi guys,

Thanks again for this app, I love it !

I just wanted to report that the display of half days leaves on the calendar view is kind of weird, at first I thought it was a bug, but later I realized it was in fact half days leaves.
When the leaves are on the morning, day numbers are displayed in white on a white background so it's not easy to read. See the screenshot below:
<img width="613" alt="screenshot 2016-12-22 at 16 08 01" src="https://cloud.githubusercontent.com/assets/2115259/21429865/f27d9d0e-c860-11e6-8a23-b74a3cba61a1.png">

**Comment by vpp** [comment]
hi @j-ledoux,

Thank you for reporting.

Your are absolutely right that the UX needs more love.

Within this ticket we are going to fix the issue you raised about rendering half days.

**Comment by vpp** [comment]
Recently CSS was updated to have cells with leaves to be of black font.
